/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.appsearch.app;

import android.os.Parcel;
import android.os.Parcelable;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.OptIn;
import androidx.annotation.RequiresFeature;
import androidx.annotation.RestrictTo;
import androidx.appsearch.flags.FlaggedApi;
import androidx.appsearch.flags.Flags;
import androidx.appsearch.safeparcel.AbstractSafeParcelable;
import androidx.appsearch.safeparcel.SafeParcelable;
import androidx.appsearch.safeparcel.stub.StubCreators.EmbeddingVectorCreator;
import androidx.appsearch.safeparcel.stub.StubCreators.QuantizedDataCreator;
import androidx.core.util.Preconditions;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Arrays;
import java.util.Objects;

/**
 * Embeddings are vector representations of data, such as text, images, and audio, which can be
 * generated by machine learning models and used for semantic search. This class represents an
 * embedding vector, which wraps a float array for the values of the embedding vector and a model
 * signature that can be any string to distinguish between embedding vectors generated by different
 * models.
 *
 * <p>For more details on how embedding search works, check {@link AppSearchSession#search} and
 * {@link SearchSpec.Builder#setRankingStrategy(String)}.
 *
 * @see SearchSpec.Builder#addEmbeddingParameters
 * @see GenericDocument.Builder#setPropertyEmbedding
 */
@RequiresFeature(
        enforcement = "androidx.appsearch.app.Features#isFeatureSupported",
        name = Features.SCHEMA_EMBEDDING_PROPERTY_CONFIG)
@SafeParcelable.Class(creator = "EmbeddingVectorCreator")
// TODO(b/384721898): Switching to JSpecify annotations changes APIs once synced to platform.
//  Do not switch until this is resolved.
@SuppressWarnings({"HiddenSuperclass", "JSpecifyNullness"})
@OptIn(markerClass = ExperimentalAppSearchApi.class)
public final class EmbeddingVector extends AbstractSafeParcelable {

    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static final @NonNull Parcelable.Creator<EmbeddingVector> CREATOR =
            new EmbeddingVectorCreator();

    private static final float EPSILON = 1e-5f;

    @Field(id = 1, getter = "getValues")
    private final @NonNull float[] mValues;

    @Field(id = 2, getter = "getModelSignature")
    private final @NonNull String mModelSignature;

    @Field(id = 3, getter = "getQuantizedData")
    private final @Nullable QuantizedData mQuantizedData;

    private @Nullable Integer mHashCode;

    /**
     * Holds the pre-quantized embedding values along with the quantization parameters.
     *
     * <p>The original float values can be reconstructed from the quantized byte values using the
     * formula: {@code originalValue = (quantizedValue / scale) + minValue}.
     */
    @ExperimentalAppSearchApi
    @FlaggedApi(Flags.FLAG_ENABLE_EMBEDDING_PRE_QUANTIZED_DATA)
    @SafeParcelable.Class(creator = "QuantizedDataCreator")
    @SuppressWarnings("HiddenSuperclass")
    public static final class QuantizedData extends AbstractSafeParcelable {

        @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
        public static final @NonNull Parcelable.Creator<QuantizedData> CREATOR =
                new QuantizedDataCreator();

        @Field(id = 1, getter = "getMinValue")
        private final float mMinValue;

        @Field(id = 2, getter = "getScale")
        private final float mScale;

        @Field(id = 3, getter = "getQuantizedValues")
        private final @NonNull byte[] mQuantizedValues;

        /**
         * Creates a new {@link QuantizedData}.
         *
         * <p>The original float values can be reconstructed from the quantized byte values using
         * the formula: {@code originalValue = (quantizedValue / scale) + minValue}.
         *
         * @param minValue The minimum float value across all dimensions before quantization.
         * @param scale The scaling factor used to quantize the vector.
         * @param quantizedValues The pre-quantized int8 vector data.
         * @throws IllegalArgumentException if {@code quantizedValues} is empty.
         */
        @Constructor
        public QuantizedData(
                @Param(id = 1) float minValue,
                @Param(id = 2) float scale,
                @Param(id = 3) @NonNull byte[] quantizedValues) {
            mMinValue = minValue;
            mScale = scale;
            mQuantizedValues = Preconditions.checkNotNull(quantizedValues);
            Preconditions.checkArgument(
                    quantizedValues.length > 0, "quantizedValues cannot be empty");
        }

        /** Returns the minimum float value across all dimensions before quantization. */
        public float getMinValue() {
            return mMinValue;
        }

        /** Returns the scaling factor used to quantize the vector. */
        public float getScale() {
            return mScale;
        }

        /** Returns the pre-quantized int8 vector data. */
        public @NonNull byte[] getQuantizedValues() {
            return mQuantizedValues;
        }

        /**
         * @exportToFramework:hide
         */
        @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
        public @NonNull byte[] getPackedBytes() {
            ByteBuffer buffer =
                    ByteBuffer.allocate(8 + mQuantizedValues.length).order(ByteOrder.LITTLE_ENDIAN);
            buffer.putFloat(mMinValue);
            buffer.putFloat(mScale);
            buffer.put(mQuantizedValues);
            return buffer.array();
        }

        @Override
        public boolean equals(@Nullable Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            QuantizedData that = (QuantizedData) o;
            return Float.compare(that.mMinValue, mMinValue) == 0
                    && Float.compare(that.mScale, mScale) == 0
                    && Arrays.equals(mQuantizedValues, that.mQuantizedValues);
        }

        @Override
        public int hashCode() {
            int result = Objects.hash(mMinValue, mScale);
            result = 31 * result + Arrays.hashCode(mQuantizedValues);
            return result;
        }

        /**
         * Creates a new {@link QuantizedData} by quantizing the provided float values to 8-bit
         * integers.
         *
         * <p>Storing 8-bit quantized values directly helps reduce memory and disk space usage by
         * approximately 75% compared to storing full 32-bit floats.
         *
         * @param values The float values to quantize.
         * @return The {@link QuantizedData} created by quantizing the float values.
         * @throws IllegalArgumentException if {@code values} is empty.
         */
        public static @NonNull QuantizedData fromUnquantizedValues(@NonNull float[] values) {
            Preconditions.checkNotNull(values);
            Preconditions.checkArgument(values.length > 0, "values cannot be empty");

            // 1. Calculate quantization parameters (min, max, scale) in a single pass
            float min = values[0];
            float max = values[0];
            for (int i = 1; i < values.length; i++) {
                min = Math.min(min, values[i]);
                max = Math.max(max, values[i]);
            }
            float scale = 0.0f;
            if (max - min > EPSILON) {
                scale = 255.0f / (max - min);
            }

            // 2. Convert floats to quantized bytes
            byte[] quantizedValues = new byte[values.length];
            for (int i = 0; i < values.length; i++) {
                int quantizedInt = Math.round((values[i] - min) * scale);
                quantizedInt = Math.max(0, Math.min(255, quantizedInt));
                quantizedValues[i] = (byte) quantizedInt;
            }

            return new QuantizedData(min, scale, quantizedValues);
        }

        @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
        @Override
        public void writeToParcel(@NonNull Parcel dest, int flags) {
            QuantizedDataCreator.writeToParcel(this, dest, flags);
        }
    }

    /**
     * Creates a new {@link EmbeddingVector} containing standard 32-bit float values.
     *
     * @param values The float values of the embedding vector.
     * @param modelSignature An arbitrary string used to distinguish between embedding vectors
     *     generated by different models.
     * @throws IllegalArgumentException if {@code values} is empty.
     */
    public EmbeddingVector(@NonNull float[] values, @NonNull String modelSignature) {
        // Calls the 3-argument constructor under the hood
        this(Preconditions.checkNotNull(values), modelSignature, /* quantizedData= */ null);
    }

    /**
     * Creates a new {@link EmbeddingVector}.
     *
     * <p>Guarantees that the embedding contains at least standard 32-bit float values or 8-bit
     * quantized values.
     *
     * @param values The original float values of the embedding vector, if available.
     * @param modelSignature An arbitrary string used to distinguish between embedding vectors
     *     generated by different models.
     * @param quantizedData The pre-quantized data containing the quantizer header and vector data,
     *     if available.
     * @throws IllegalArgumentException if neither values nor quantized data are provided.
     * @exportToFramework:hide
     */
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    @Constructor
    public EmbeddingVector(
            @Param(id = 1) @Nullable float[] values,
            @Param(id = 2) @NonNull String modelSignature,
            @Param(id = 3) @Nullable QuantizedData quantizedData) {
        Preconditions.checkNotNull(modelSignature);
        if (values != null && values.length == 0) {
            throw new IllegalArgumentException("Embedding values cannot be empty.");
        }
        if (quantizedData != null && quantizedData.getQuantizedValues().length == 0) {
            throw new IllegalArgumentException("Embedding values cannot be empty.");
        }
        boolean hasValues = values != null;
        boolean hasQuantizedData = quantizedData != null;
        Preconditions.checkArgument(
                hasValues || hasQuantizedData,
                "EmbeddingVector must have at least float values or quantized data.");
        // Older versions of the sdk require that values is non-null and non-empty.
        // We choose to provide a single entry array to avoid crashes in older
        // versions of the SDK. We believe this is the best choice because:
        //   1. Callers that are retrieving their own data would have to have an updated
        //      SDK to populate pre-quantized data. Therefore, they would be unaffected.
        //   2. We don't want to pre-populate values with un-quantized data because that
        //      would add CPU costs and bloat the memory costs of this value by 5x. The
        //      goal of pre-quantized embeddings is to shrink the size of the data.
        //      providing both versions of the embeddings would defeat the purpose of this
        //      feature.
        // TODO(b/514770535): include a version number in requests to decide whether to
        //  pre-populate field.
        mValues = !hasValues ? new float[]{0.0f} : values;
        mModelSignature = modelSignature;
        mQuantizedData = quantizedData;
    }

    /**
     * Creates a new {@link EmbeddingVector} from pre-quantized embedding data.
     *
     * <p>Storing 8-bit quantized values directly helps reduce memory and disk space usage by
     * approximately 75% compared to storing full 32-bit floats.
     *
     * @param quantizedData The pre-quantized embedding data.
     * @param modelSignature An arbitrary string used to distinguish between embedding vectors
     *     generated by different models.
     * @throws IllegalArgumentException if {@code quantizedData} contains empty values.
     */
    @ExperimentalAppSearchApi
    @RequiresFeature(
            enforcement = "androidx.appsearch.app.Features#isFeatureSupported",
            name = Features.SCHEMA_EMBEDDING_PRE_QUANTIZED_DATA)
    @FlaggedApi(Flags.FLAG_ENABLE_EMBEDDING_PRE_QUANTIZED_DATA)
    public EmbeddingVector(@NonNull QuantizedData quantizedData, @NonNull String modelSignature) {
        this(/* values= */ null, modelSignature, Preconditions.checkNotNull(quantizedData));
    }

    /** Returns the values of this embedding vector. */
    public @NonNull float[] getValues() {
        return mValues;
    }

    /**
     * Returns the quantized data of this embedding vector, or null if it only contains standard
     * float values.
     */
    @ExperimentalAppSearchApi
    @FlaggedApi(Flags.FLAG_ENABLE_EMBEDDING_PRE_QUANTIZED_DATA)
    public @Nullable QuantizedData getQuantizedData() {
        return mQuantizedData;
    }

    /**
     * Returns the model signature of this embedding vector, which is an arbitrary string to
     * distinguish between embedding vectors generated by different models.
     */
    public @NonNull String getModelSignature() {
        return mModelSignature;
    }

    @Override
    public boolean equals(@Nullable Object o) {
        if (this == o) {
            return true;
        }
        if (o == null) {
            return false;
        }
        if (!(o instanceof EmbeddingVector)) {
            return false;
        }
        EmbeddingVector that = (EmbeddingVector) o;
        return Arrays.equals(mValues, that.mValues)
                && mModelSignature.equals(that.mModelSignature)
                && Objects.equals(mQuantizedData, that.mQuantizedData);
    }

    @Override
    public int hashCode() {
        if (mHashCode == null) {
            mHashCode = Objects.hash(Arrays.hashCode(mValues), mModelSignature, mQuantizedData);
        }
        return mHashCode;
    }

    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        EmbeddingVectorCreator.writeToParcel(this, dest, flags);
    }
}
