package androidx.appfunctions.`internal`

import com.testdata.`$IntEnumValueFunctions_AppFunctionInventory`
import javax.`annotation`.processing.Generated
import kotlin.collections.List

@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$AggregatedAppFunctionInventory_Impl` : AggregatedAppFunctionInventory() {
  override val inventories: List<AppFunctionInventory> = listOf(
    `$IntEnumValueFunctions_AppFunctionInventory`(),
  )
}
