ext.configureForkBuildscript = { ScriptHandler buildscriptHandler ->
    buildscriptHandler.with {
        ext.supportRootFolder = buildscript.sourceFile.getParentFile()
        apply(from: "buildSrc/repos.gradle")
        apply(from: "buildSrc/settingsScripts/project-dependency-graph.groovy")
        apply(from: "buildSrc/settingsScripts/skiko-setup.groovy")

        repos.addMavenRepositories(repositories)

        dependencies {
            // upgrade protobuf to be compatible with AGP
            classpath("com.google.protobuf:protobuf-java:3.25.5")
            classpath("com.gradle:develocity-gradle-plugin:4.3")
            classpath("com.gradle:common-custom-user-data-gradle-plugin:2.4.0")
            classpath("androidx.build.gradle.gcpbuildcache:gcpbuildcache:1.0.0")
            classpath("com.google.cloud:google-cloud-secretmanager:2.67.0")
            def agpOverride = System.getenv("GRADLE_PLUGIN_VERSION")
            if (agpOverride != null) {
                classpath("com.android.settings:com.android.settings.gradle.plugin:$agpOverride")
            } else {
                classpath("com.android.settings:com.android.settings.gradle.plugin:8.12.0")
            }
            // set guava version to be compatible with Depdendency analysis gradle plugin
            classpath("com.google.guava:guava:33.3.1-jre")
        }
    }
}