/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.pdf.annotation

import androidx.annotation.RestrictTo
import androidx.pdf.annotation.models.PdfAnnotation

/** Callback interface for events related to the creation and modification of annotations. */
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public interface OnAnnotationEditListener {

    /**
     * Called when an in-progress interaction successfully produces a finalized [PdfAnnotation].
     *
     * @param annotation The finalized [PdfAnnotation] object containing the metadata generated by
     *   the user's interaction.
     */
    public fun onAnnotationCreated(annotation: PdfAnnotation)

    /**
     * Called when a failure occurs during the creation or modification of an annotation.
     *
     * @param throwable The underlying cause of the failure.
     */
    public fun onAnnotationError(throwable: Throwable)
}
