/*
 * Copyright 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was created using the `createProject` gradle task (./gradlew createProject)
 *
 * Please use the task when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import org.gradle.api.attributes.java.TargetJvmEnvironment
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("AndroidXPlugin")
    id("AndroidXComposePlugin")
    id("com.android.library")
}

configurations {
    // Configuration to access internal implementation of foundation library
    // This removes need for suppressing INVISIBLE_REFERENCE and INVISIBLE_MEMBER in codebase
    // IDE does not support this configuration yet, so you will still see references to internal
    // members marked as an error. You can ignore them.
    friends {
        canBeResolved = true
        canBeConsumed = false
        transitive = false
        attributes {
            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_API))
            attribute(TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(TargetJvmEnvironment, TargetJvmEnvironment.ANDROID))
            attribute(Attribute.of("artifactType", String), "android-classes-jar")
        }
    }
    androidTestImplementation.extendsFrom(friends)
}

android {
    compileSdk { version = release(37) }
    namespace = "androidx.compose.foundation.lazytests"
}

dependencies {
    friends(project(":compose:foundation:foundation"))
    androidTestImplementation(project(":compose:test-utils"))
    androidTestImplementation(project(":compose:ui:ui"))
    androidTestImplementation(project(":internal-testutils-fonts"))
    androidTestImplementation(project(":test:screenshot:screenshot"))
    androidTestImplementation(project(":internal-testutils-runtime"))
    androidTestImplementation("androidx.activity:activity-compose:1.3.1")
    androidTestImplementation("androidx.lifecycle:lifecycle-runtime:2.6.1")
    androidTestImplementation("androidx.savedstate:savedstate:1.2.1")

    androidTestImplementation(libs.kotlinTest)
    androidTestImplementation(libs.kotlinCoroutinesTest)
    androidTestImplementation(libs.testUiautomator)
    androidTestImplementation(libs.testRules)
    androidTestImplementation(libs.testRunner)
    androidTestImplementation(libs.testMonitor)
    androidTestImplementation(libs.espressoCore)
    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.truth)
    androidTestImplementation(libs.dexmakerMockito)
    androidTestImplementation(libs.mockitoCore)
    androidTestImplementation(libs.mockitoKotlin)
}

androidx.deviceTests.minSdkForFtlOverride = 24 // b/437944630

tasks.withType(KotlinCompile).configureEach {
    it.friendPaths.from(configurations.friends.incoming.files)
}
