/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.appfunctions.compiler.processors

import androidx.appfunctions.compiler.testings.CompilationTestHelper
import java.io.File
import org.junit.Before
import org.junit.Test

class AppFunctionEntryPointCompilerTest {
    private lateinit var compilationTestHelper: CompilationTestHelper

    @Before
    fun setup() {
        compilationTestHelper =
            CompilationTestHelper(
                testFileSrcDir = File("src/test/test-data/input"),
                goldenFileSrcDir = File("src/test/test-data/output"),
                stubSourceFileNames = listOf(),
                symbolProcessorProviders = listOf(AppFunctionEntryPointProcessor.Provider()),
            )
    }

    @Test
    fun testAppFunctionEntryPoint_generatesServiceClass() {
        val report =
            compilationTestHelper.compileAll(
                sourceFileNames = listOf("entrypoints/valid/SimpleEntryPoint.KT"),
                processorOptions = emptyMap(),
            )

        compilationTestHelper.assertSuccessWithSourceContent(
            report = report,
            expectGeneratedSourceFileName = "MySimpleService.kt",
            goldenFileName = "entrypoints/MySimpleService.KT",
        )
    }

    @Test
    fun testMissingSuperClass_hasCompileError() {
        val report =
            compilationTestHelper.compileAll(
                sourceFileNames = listOf("entrypoints/invalid/MissingSuperClassEntryPoint.KT"),
                processorOptions = emptyMap(),
            )

        compilationTestHelper.assertErrorWithMessage(
            report,
            "Class must extend androidx.appfunctions.AppFunctionService",
        )
    }

    @Test
    fun testNotAbstract_hasCompileError() {
        val report =
            compilationTestHelper.compileAll(
                sourceFileNames = listOf("entrypoints/invalid/NotAbstractEntryPoint.KT"),
                processorOptions = emptyMap(),
            )

        compilationTestHelper.assertErrorWithMessage(
            report,
            "The class being annotated with AppFunctionEntryPoint should be an abstract class",
        )
    }

    @Test
    fun testImplementedExecuteFunction_hasCompileError() {
        val report =
            compilationTestHelper.compileAll(
                sourceFileNames =
                    listOf("entrypoints/invalid/ImplementedExecuteFunctionEntryPoint.KT"),
                processorOptions = emptyMap(),
            )

        compilationTestHelper.assertErrorWithMessage(
            report,
            "The abstract class cannot implement executeFunction. This would be generated by the compiler",
        )
    }

    @Test
    fun testEmptyAppFunctionEntryPoint_hasCompileError() {
        val report =
            compilationTestHelper.compileAll(
                sourceFileNames = listOf("entrypoints/invalid/EmptyAppFunctionEntryPoint.KT"),
                processorOptions = emptyMap(),
            )

        compilationTestHelper.assertErrorWithMessage(
            report,
            "Class must have at least one AppFunction",
        )
    }
}
