blank_issues_enabled: false
contact_links:
  - name: Activity
    url: https://issuetracker.google.com/issues/new?component=527362&template=1189829
    about: File a bug or feature request for Activity
  - name: Biometric
    url: https://issuetracker.google.com/issues/new?component=559537&template=1214425
    about: File a bug or feature request for Biometric
  - name: Camera
    url: https://issuetracker.google.com/issues/new?component=618491&template=1257717
    about: File a bug or feature request for Camera
  - name: Collection
    url: https://b.corp.google.com/issues/new?component=460756&template=1422573
    about: File a bug or feature request for Collection
  - name: Compose Compiler
    url: https://issuetracker.google.com/issues/new?component=610764&template=1424126
    about: File a bug or feature request for Compose Compiler
  - name: DataStore
    url: https://issuetracker.google.com/issues/new?component=907884&template=1466542
    about: File a bug or feature request for DataStore
  - name: Fragment
    url: https://issuetracker.google.com/issues/new?component=460964&template=1182267
    about: File a bug or feature request for Fragment
  - name: Lifecycle
    url: https://issuetracker.google.com/issues/new?component=413132&template=1096619
    about: File a bug or feature request for Lifecycle
  - name: Navigation
    url: https://issuetracker.google.com/issues/new?component=409828&template=1093757
    about: File a bug or feature request for Navigation
  - name: Paging
    url: https://issuetracker.google.com/issues/new?component=413106&template=1096385
    about: File a bug or feature request for Paging
  - name: Room
    url: https://issuetracker.google.com/issues/new?component=413107&template=1096568
    about: File a bug or feature request for Room
  - name: WorkManager
    url: https://issuetracker.google.com/issues/new?component=409906&template=1094197
    about: File a bug or feature request for WorkManager
