/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:JvmName("KClassUtil")
@file:JvmMultifileClass
@file:RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)

package androidx.room3.util

import androidx.annotation.RestrictTo
import androidx.room3.RoomDatabase
import kotlin.jvm.JvmMultifileClass
import kotlin.jvm.JvmName
import kotlin.reflect.KClass

/**
 * Finds the [androidx.room3.RoomDatabaseConstructor] of this class linked via
 * [androidx.room3.ConstructedBy] and invoke its function to create an instance of the
 * implementation class generated by Room of an `@Database` annotated type.
 */
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP_PREFIX)
public expect fun <T : RoomDatabase> findDatabaseConstructorAndInitDatabaseImpl(klass: KClass<*>): T

@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public actual fun KClass<*>.getQualifiedName(): String? = this.simpleName
