box {
  width {
    expanded_dimension {}
  }
  height {
    expanded_dimension {}
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 0
      }
      vertical_align {
        value: VERTICAL_ALIGN_TOP
      }
      contents {
        adapter {
          content {
            box {
              horizontal_alignment {
                value: HORIZONTAL_ALIGN_CENTER
              }
              vertical_alignment {
                value: VERTICAL_ALIGN_CENTER
              }
              modifiers {
                background {
                  color {
                    argb: 0xFFFF0000
                  }
                  corner {
                    radius {
                      value: 12
                    }
                  }
                }
              }
              contents {
                spacer {
                  width {
                    linear_dimension {
                      value: 24
                    }
                  }
                  height {
                    linear_dimension {
                      value: 24
                    }
                  }
                }
              }
              contents {
                text {
                  text {
                    value: "T"
                  }
                  font_style {
                    weight {
                      value: FONT_WEIGHT_BOLD
                    }
                    size {
                      value: 16
                    }
                    color {
                      argb: 0xFFFFFFFF
                    }
                  }
                }
              }
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 20
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 60
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 90
      }
      vertical_align {
        value: VERTICAL_ALIGN_CENTER
      }
      contents {
        adapter {
          content {
            box {
              horizontal_alignment {
                value: HORIZONTAL_ALIGN_CENTER
              }
              vertical_alignment {
                value: VERTICAL_ALIGN_CENTER
              }
              modifiers {
                background {
                  color {
                    argb: 0xFFFF0000
                  }
                  corner {
                    radius {
                      value: 12
                    }
                  }
                }
              }
              contents {
                spacer {
                  width {
                    linear_dimension {
                      value: 24
                    }
                  }
                  height {
                    linear_dimension {
                      value: 24
                    }
                  }
                }
              }
              contents {
                text {
                  text {
                    value: "C"
                  }
                  font_style {
                    weight {
                      value: FONT_WEIGHT_BOLD
                    }
                    size {
                      value: 16
                    }
                    color {
                      argb: 0xFFFFFFFF
                    }
                  }
                }
              }
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 20
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 60
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 180
      }
      vertical_align {
        value: VERTICAL_ALIGN_BOTTOM
      }
      contents {
        adapter {
          content {
            box {
              horizontal_alignment {
                value: HORIZONTAL_ALIGN_CENTER
              }
              vertical_alignment {
                value: VERTICAL_ALIGN_CENTER
              }
              modifiers {
                background {
                  color {
                    argb: 0xFFFF0000
                  }
                  corner {
                    radius {
                      value: 12
                    }
                  }
                }
              }
              contents {
                spacer {
                  width {
                    linear_dimension {
                      value: 24
                    }
                  }
                  height {
                    linear_dimension {
                      value: 24
                    }
                  }
                }
              }
              contents {
                text {
                  text {
                    value: "B"
                  }
                  font_style {
                    weight {
                      value: FONT_WEIGHT_BOLD
                    }
                    size {
                      value: 16
                    }
                    color {
                      argb: 0xFFFFFFFF
                    }
                  }
                }
              }
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 20
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 60
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 270
      }
      contents {
        adapter {
          content {
            box {
              horizontal_alignment {
                value: HORIZONTAL_ALIGN_CENTER
              }
              vertical_alignment {
                value: VERTICAL_ALIGN_CENTER
              }
              modifiers {
                background {
                  color {
                    argb: 0xFFFF0000
                  }
                  corner {
                    radius {
                      value: 12
                    }
                  }
                }
              }
              contents {
                spacer {
                  width {
                    linear_dimension {
                      value: 24
                    }
                  }
                  height {
                    linear_dimension {
                      value: 24
                    }
                  }
                }
              }
              contents {
                text {
                  text {
                    value: "DEF"
                  }
                  font_style {
                    weight {
                      value: FONT_WEIGHT_BOLD
                    }
                    size {
                      value: 16
                    }
                    color {
                      argb: 0xFFFFFFFF
                    }
                  }
                }
              }
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 20
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 60
          }
        }
      }
    }
  }
}

