box {
  width {
    expanded_dimension {}
  }
  height {
    expanded_dimension {}
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 0
      }
      vertical_align {
        value: VERTICAL_ALIGN_TOP
      }
      contents {
        text {
          text {
            value: "TOP"
          }
          font_style {
            weight {
              value: FONT_WEIGHT_BOLD
            }
            size {
              value: 16
            }
            color {
              argb: 0xFFFF0000
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 15
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 50
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 90
      }
      vertical_align {
        value: VERTICAL_ALIGN_CENTER
      }
      contents {
        text {
          text {
            value: "CENTER"
          }
          font_style {
            weight {
              value: FONT_WEIGHT_BOLD
            }
            size {
              value: 16
            }
            color {
              argb: 0xFFFF0000
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 15
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 50
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 180
      }
      vertical_align {
        value: VERTICAL_ALIGN_BOTTOM
      }
      contents {
        text {
          text {
            value: "BOT"
          }
          font_style {
            weight {
              value: FONT_WEIGHT_BOLD
            }
            size {
              value: 16
            }
            color {
              argb: 0xFFFF0000
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 15
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 50
          }
        }
      }
    }
  }

  contents {
    arc {
      anchor_type: {
        value: ARC_ANCHOR_START
      }
      anchor_angle: {
        value: 270
      }
      contents {
        text {
          text {
            value: "DEF"
          }
          font_style {
            weight {
              value: FONT_WEIGHT_BOLD
            }
            size {
              value: 16
            }
            color {
              argb: 0xFFFF0000
            }
          }
        }
      }
      contents {
        spacer {
          length {
            value: 15
          }
        }
      }
      contents {
        line {
          color {
            argb: 0xFF00FF00
          }
          length {
            value: 10
          }
          thickness {
            value: 50
          }
        }
      }
    }
  }
}
