column {
  contents {
    column {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_LEFT
      }
      contents {
        text {
          text {
            value: "Align"
          }
        }
      }
      contents {
        text {
          text {
            value: "L"
          }
        }
      }
    }
  }

  contents {
    column {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_CENTER
      }
      contents {
        text {
          text {
            value: "Align"
          }
        }
      }
      contents {
        text {
          text {
            value: "MID"
          }
        }
      }
    }
  }

  contents {
    column {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_RIGHT
      }
      contents {
        text {
          text {
            value: "Align"
          }
        }
      }
      contents {
        text {
          text {
            value: "R"
          }
        }
      }
    }
  }

  contents {
    column {
      contents {
        text {
          text {
            value: "Align undefined"
          }
        }
      }
      contents {
        text {
          text {
            value: "MID"
          }
        }
      }
    }
  }
}
