# This is a bit of a contrived example.
# Add a column with minimal contents into a box, and align the box contents to
# the bottom. If the column didn't have a height, it would just wrap its
# contents and draw them at the bottom of the box. If the column has a height
# then it will start placing elements from the top of the column, hence the
# contents will be inset from the bottom of the parent box.
box {
  width {
    expanded_dimension {}
  }
  height {
    expanded_dimension {}
  }
  vertical_alignment {
    value: VERTICAL_ALIGN_BOTTOM
  }
  modifiers {
    background {
      color {
        argb: 0xFFFF0000
      }
    }
  }
  contents {
    column {
      height {
        linear_dimension {
          value: 100
        }
      }
      contents {
        text {
          text {
            value: "Hi"
          }
        }
      }
      contents {
        text {
          text {
            value: "World"
          }
        }
      }
    }
  }
}
