# Check that a box's width will be set even when its style is not set.
# See b/165807783
box {
  width {
    expanded_dimension {}
  }
  contents {
    box {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_END
      }
      modifiers {
        background {
          color {
            argb: 0xFFFF0000
          }
        }
      }
      width {
        expanded_dimension {}
      }
      contents {
        text {
          text {
            value: "Right-Aligned Text"
          }
        }
      }
    }
  }
}
