spannable {
  max_lines {
    value: 5
  }
  multiline_alignment {
    value: HORIZONTAL_ALIGN_START
  }
  line_spacing {
    value: 20
  }
  spans {
    text {
      font_style {
        weight {
          value: FONT_WEIGHT_NORMAL
        }
        color {
          argb: 0xFFFF0000
        }
      }
      text {
        value: "Normal "
      }
    }
  }
  spans {
    text {
      font_style {
        weight {
          value: FONT_WEIGHT_BOLD
        }
        color {
          argb: 0xFFFF0000
        }
      }
      text {
        value: "Bold"
      }
    }
  }
}
