column {
  contents {
    text {
      text {
        value: "Fit"
      }
    }
  }
  contents {
    box {
      modifiers {
        border {
          width {
            value: 1
          }
          color {
            argb: 0xFFFF0000
          }
        }
      }
      contents {
        image {
          width {
            linear_dimension {
              value: 48
            }
          }
          height {
            linear_dimension {
              value: 24
            }
          }
          resource_id {
            value: "android_withbg_120dp"
          }
          content_scale_mode {
            value: CONTENT_SCALE_MODE_FIT
          }
        }
      }
    }
  }

  contents {
    text {
      text {
        value: "Crop"
      }
    }
  }

  contents {
    box {
      modifiers {
        border {
          width {
            value: 1
          }
          color {
            argb: 0xFFFF0000
          }
        }
      }
      contents {
        image {
          width {
            linear_dimension {
              value: 48
            }
          }
          height {
            linear_dimension {
              value: 24
            }
          }
          resource_id {
            value: "android_withbg_120dp"
          }
          content_scale_mode {
            value: CONTENT_SCALE_MODE_CROP
          }
        }
      }
    }
  }

  contents {
    text {
      text {
        value: "FillBounds"
      }
    }
  }
  contents {
    box {
      modifiers {
        border {
          width {
            value: 1
          }
          color {
            argb: 0xFFFF0000
          }
        }
      }
      contents {
        image {
          width {
            linear_dimension {
              value: 48
            }
          }
          height {
            linear_dimension {
              value: 24
            }
          }
          resource_id {
            value: "android_withbg_120dp"
          }
          content_scale_mode {
            value: CONTENT_SCALE_MODE_FILL_BOUNDS
          }
        }
      }
    }
  }
}
