column {
  contents {
    spacer {
      width {
        linear_dimension {
          value: 100
        }
      }
      height {
        linear_dimension {
          value: 10
        }
      }
      modifiers {
        background {
          color {
            argb: 0xFFFF0000
          }
          corner {
            radius {
              value: 5
            }
          }
        }
      }
    }
  }
  contents {
    spacer {
      width {
        linear_dimension {
          value: 100
        }
      }
      height {
        linear_dimension {
          value: 20
        }
      }
      modifiers {
        background {
          color {
            argb: 0xFF00FF00
          }
        }
      }
    }
  }
  contents {
    spacer {
      width {
        linear_dimension {
          value: 100
        }
      }
      height {
        linear_dimension {
          value: 40
        }
      }
      modifiers {
        background {
          color {
            argb: 0xFFFFFF00
          }
          corner {
            radius {
              value: 20
            }
          }
        }
      }
    }
  }
  contents {
    spacer {
      width {
        linear_dimension {
          value: 100
        }
      }
      height {
        linear_dimension {
          value: 50
        }
      }
      modifiers {
        background {
          color {
            argb: 0xFF00FFFF
          }
          corner {
            radius {
              value: 25
            }
          }
        }
      }
    }
  }
  contents {
    box {
      modifiers {
        background {
          color {
            argb: 0xFFFFFF00
          }
        }
      }
      contents {
        row {
          contents {
            text {
              text {
                value: "0-length line ->"
              }
              font_style {
                size {
                  value: 14
                }
                weight {
                  value: FONT_WEIGHT_BOLD
                }
                color {
                  argb: 0xFF000000
                }
              }
            }
          }
          contents {
            # Spacer with no length but a thickness of 40dp.
            spacer {
              height {
                linear_dimension {
                  value: 40
                }
              }
              modifiers {
                background {
                  color {
                    argb: 0xFF000000
                  }
                  corner {
                    radius {
                      value: 20
                    }
                  }
                }
              }
            }
          }
          contents {
            text {
              text {
                value: "<-"
              }
              font_style {
                size {
                  value: 14
                }
                weight {
                  value: FONT_WEIGHT_BOLD
                }
                color {
                  argb: 0xFF000000
                }
              }
            }
          }
        }
      }
    }
  }
  contents {
    box {
      modifiers {
        background {
          color {
            argb: 0xFF00FF00
          }
        }
      }
      contents {
        column {
          horizontal_alignment {
            value: HORIZONTAL_ALIGN_START
          }
          contents {
            text {
              text {
                value: "v 0-thickness line"
              }
              font_style {
                size {
                  value: 14
                }
                weight {
                  value: FONT_WEIGHT_BOLD
                }
                color {
                  argb: 0xFF000000
                }
              }
            }
          }
          contents {
            spacer {
              # Spacer with no thickness but a length of 160dp.
              width {
                linear_dimension {
                  value: 160
                }
              }
              modifiers {
                background {
                  color {
                    argb: 0xFF000000
                  }
                }
              }
            }
          }
          contents {
            text {
              text {
                value: "^"
              }
              font_style {
                size {
                  value: 14
                }
                weight {
                  value: FONT_WEIGHT_BOLD
                }
                color {
                  argb: 0xFF000000
                }
              }
            }
          }
        }
      }
    }
  }
  contents {
    box {
      modifiers {
        background {
          color {
            argb: 0xFF0000FF
          }
        }
      }
      contents {
        spacer {
          # Spacer with no dimensions. Neither the spacer nor the blue container
          # around it should be visible.
          modifiers {
            background {
              color {
                argb: 0xFF000000
              }
            }
          }
        }
      }
    }
  }
}
