column {
  contents {
    row {
      vertical_alignment {
        value: VERTICAL_ALIGN_TOP
      }
      contents {
        image {
          resource_id {
            value: "android"
          }
          width {
            linear_dimension {
              value: 45
            }
          }
          height {
            linear_dimension {
              value: 45
            }
          }
        }
      }
      contents {
        text {
          text {
            value: "T"
          }
        }
      }
    }
  }

  contents {
    row {
      vertical_alignment {
        value: VERTICAL_ALIGN_CENTER
      }
      contents {
        image {
          resource_id {
            value: "android"
          }
          width {
            linear_dimension {
              value: 45
            }
          }
          height {
            linear_dimension {
              value: 45
            }
          }
        }
      }
      contents {
        text {
          text {
            value: "MID"
          }
        }
      }
    }
  }

  contents {
    row {
      vertical_alignment {
        value: VERTICAL_ALIGN_BOTTOM
      }
      contents {
        image {
          resource_id {
            value: "android"
          }
          width {
            linear_dimension {
              value: 45
            }
          }
          height {
            linear_dimension {
              value: 45
            }
          }
        }
      }
      contents {
        text {
          text {
            value: "B"
          }
        }
      }
    }
  }

  contents {
    row {
      contents {
        image {
          resource_id {
            value: "android"
          }
          width {
            linear_dimension {
              value: 45
            }
          }
          height {
            linear_dimension {
              value: 45
            }
          }
        }
      }
      contents {
        text {
          text {
            value: "Default (MID)"
          }
        }
      }
    }
  }
}
