spannable {
  max_lines {
    value: 5
  }
  multiline_alignment {
    value: HORIZONTAL_ALIGN_START
  }
  spans {
    text {
      font_style {
        color {
          argb: 0xFFFF0000
        }
      }
      text {
        value: "Hello"
      }
    }
  }
  spans {
    image {
      resource_id {
        value: "android"
      }
      width {
        value: 24
      }
      height {
        value: 24
      }
      modifiers {
        clickable {
          id: "HelloWorld"
          on_click {
            load_action {}
          }
        }
      }
    }
  }
  spans {
    text {
      font_style {
        color {
          argb: 0xFF00FF00
        }
      }
      text {
        value: "World"
      }
    }
  }
}
