row {
  contents {
    text {
      text {
        value: "This"
      }
      font_style {
        color {
          argb: 0xFFFF0000
        }
      }
    }
  }
  contents {
    text {
      text {
        value: "Is"
      }
      font_style {
        color {
          argb: 0xFF00FF00
        }
      }
    }
  }
  contents {
    text {
      text {
        value: "A"
      }
      font_style {
        color {
          argb: 0xFF0000FF
        }
      }
    }
  }
  contents {
    text {
      text {
        value: "Test"
      }
      font_style {
        color {
          argb: 0xFF00FFFF
        }
      }
    }
  }
}
