box {
  modifiers {
    background {
      color {
        argb: 0xFF000000
      }
    }
  }
  width {
    expanded_dimension: {}
  }
  height {
    expanded_dimension: {}
  }
  vertical_alignment {
    value: VERTICAL_ALIGN_CENTER
  }
  horizontal_alignment {
    value: HORIZONTAL_ALIGN_CENTER
  }
  contents {
    column {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_LEFT
      }
      contents {
        text {
          text {
            value: "Normal height"
          }
          font_style {
            size { value: 14 }
          }
        }
      }
      contents {
        text {
          text {
            value: "size 14sp, lineHeight 34sp. This should be a longer text to show the baseline distance."
          }
          max_lines { value: 10 }
          line_height { value: 34 }
          font_style {
            size { value: 14 }
          }
        }
      }
      contents {
        text {
          text {
            value: "size 14sp, letterSpacing 0.5em"
          }
          max_lines { value: 10 }
          font_style {
            size { value: 14 }
            letter_spacing { value: 0.5 }
          }
        }
      }
      contents {
        text {
          text {
            value: "size 14sp, letterSpacing -0.1em"
          }
          font_style {
            size { value: 14 }
            letter_spacing { value: -0.1 }
          }
        }
      }
    }
  }
}
