box {
  modifiers {
    background {
      color {
        argb: 0xFF000000
      }
    }
  }
  width {
    expanded_dimension: {}
  }
  height {
    expanded_dimension: {}
  }
  vertical_alignment {
    value: VERTICAL_ALIGN_CENTER
  }
  horizontal_alignment {
    value: HORIZONTAL_ALIGN_CENTER
  }
  contents {
    column {
      horizontal_alignment {
        value: HORIZONTAL_ALIGN_LEFT
      }
      contents {
        text {
          text {
            value: "Weight=Unset (Normal)"
          }
          font_style {
            size { value: 14 }
          }
        }
      }
      contents {
        text {
          text {
            value: "Weight=Undefined (Normal)"
          }
          font_style {
            size { value: 14 }
            weight { value: FONT_WEIGHT_UNDEFINED }
          }
        }
      }
      contents {
        text {
          text {
            value: "Weight=400 (Normal)"
          }
          font_style {
            size { value: 14 }
            weight { value: FONT_WEIGHT_NORMAL }
          }
        }
      }
      contents {
        text {
          text {
            value: "Weight=700 (Bold)"
          }
          font_style {
            size { value: 14 }
            weight { value: FONT_WEIGHT_BOLD }
          }
        }
      }
    }
  }
}
