/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.appfunctions.compiler.core

import androidx.appfunctions.compiler.core.IntrospectionHelper.AppFunctionEntryPointAnnotation
import androidx.appfunctions.compiler.core.IntrospectionHelper.AppFunctionServiceClass
import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Modifier

/** Represents a class annotated with @AppFunctionEntryPoint. */
class AnnotatedAppFunctionEntryPoint(
    val serviceDeclaration: KSClassDeclaration,
    val appFunctions: List<AnnotatedAppFunction>,
) {
    private val appFunctionEntryPointAnnotation by lazy {
        serviceDeclaration.annotations.findAnnotation(AppFunctionEntryPointAnnotation.CLASS_NAME)
            ?: throw ProcessingException(
                "Class not annotated with @AppFunctionEntryPoint",
                serviceDeclaration,
            )
    }

    /** The name of the service class. */
    val serviceName: String by lazy {
        appFunctionEntryPointAnnotation.requirePropertyValueOfType(
            AppFunctionEntryPointAnnotation.PROPERTY_SERVICE_NAME,
            String::class,
        )
    }

    /** The name of the app function XML file. */
    val appFunctionXmlFileName: String by lazy {
        appFunctionEntryPointAnnotation.requirePropertyValueOfType(
            AppFunctionEntryPointAnnotation.PROPERTY_APP_FUNCTION_XML_FILE_NAME,
            String::class,
        )
    }

    /** Validates the app function entry point. */
    fun validate(): AnnotatedAppFunctionEntryPoint {
        validateAnnotation()
        validateSuperClass()
        validateIsAbstract()
        validateExecuteFunctionIsNotImplemented()
        validateAppFunctions()
        return this
    }

    /**
     * Returns the set of files that need to be processed to obtain the complete information about
     * the app function entry point.
     */
    fun getSourceFiles(): Set<KSFile> {
        val sourceFileSet: MutableSet<KSFile> = mutableSetOf()

        serviceDeclaration.containingFile?.let { sourceFileSet.add(it) }

        for (appFunction in appFunctions) {
            sourceFileSet.addAll(appFunction.getSourceFiles())
        }
        return sourceFileSet
    }

    private fun validateAnnotation() {
        val entryPointAnnotation =
            serviceDeclaration.annotations.findAnnotation(
                AppFunctionEntryPointAnnotation.CLASS_NAME
            )
        if (entryPointAnnotation == null) {
            throw ProcessingException(
                "Class must be annotated with @AppFunctionEntryPoint",
                serviceDeclaration,
            )
        }
    }

    private fun validateSuperClass() {
        val isAppFunctionService =
            serviceDeclaration.getAllSuperTypes().any {
                it.declaration.qualifiedName?.asString() ==
                    AppFunctionServiceClass.CLASS_NAME.canonicalName
            }
        if (!isAppFunctionService) {
            throw ProcessingException(
                "Class must extend ${AppFunctionServiceClass.CLASS_NAME.canonicalName}",
                serviceDeclaration,
            )
        }
    }

    private fun validateIsAbstract() {
        if (Modifier.ABSTRACT !in serviceDeclaration.modifiers) {
            throw ProcessingException(
                "The class being annotated with AppFunctionEntryPoint should be an abstract class",
                serviceDeclaration,
            )
        }
    }

    private fun validateExecuteFunctionIsNotImplemented() {
        val executeFunction =
            serviceDeclaration.declarations.filterIsInstance<KSFunctionDeclaration>().find {
                it.simpleName.asString() ==
                    AppFunctionServiceClass.ExecuteFunctionMethod.METHOD_NAME
            }
        if (executeFunction != null && Modifier.ABSTRACT !in executeFunction.modifiers) {
            throw ProcessingException(
                "The abstract class cannot implement executeFunction. This would be generated by the compiler",
                executeFunction,
            )
        }
    }

    private fun validateAppFunctions() {
        if (appFunctions.isEmpty()) {
            throw ProcessingException(
                "Class must have at least one AppFunction",
                serviceDeclaration,
            )
        }
        for (appFunction in appFunctions) {
            appFunction.validate(skipFirstParameterValidation = true)
        }
    }
}
