/*
 * Copyright 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.compose.ui.test

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.input.indirect.IndirectPointerEventPrimaryDirectionalMotionAxis
import androidx.compose.ui.platform.ViewConfiguration
import androidx.compose.ui.semantics.SemanticsNode
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.IntSize
import kotlin.math.roundToInt

/**
 * The receiver scope of the multi-modal input injection lambda from [performMultiModalInput].
 *
 * [MultiModalInjectionScope] brings together the receiver scopes of all individual modalities,
 * allowing you to inject gestures that consist of events from different modalities, like touch and
 * mouse. For each modality, there is a function to which you pass a lambda in which you can inject
 * events for that modality: currently, we have [touch], [mouse] and [key] functions. See their
 * respective docs for more information.
 *
 * Note that all events generated by the gesture methods are batched together and sent as a whole
 * after [performMultiModalInput] has executed its code block.
 *
 * Example of performing a click via touch input followed by drag and drop via mouse input:
 *
 * @sample androidx.compose.ui.test.samples.multiModalInputClickDragDrop
 * @see InjectionScope
 * @see TouchInjectionScope
 * @see MouseInjectionScope
 * @see KeyInjectionScope
 * @see RotaryInjectionScope
 * @see TrackpadInjectionScope
 */
// TODO(fresen): add better multi modal example when we have key input support
sealed interface MultiModalInjectionScope : InjectionScope {
    /** Injects all touch events sent by the given [block] */
    fun touch(block: TouchInjectionScope.() -> Unit)

    /**
     * Injects all indirect pointer events sent by the given [block]. This API requires an active
     * focus state meaning developers need to request focus to the component or a child of the
     * component via [SemanticsNodeInteraction.requestFocus()] before calling this function. If no
     * component is currently focused, the event will not trigger.
     *
     * @param indirectPointerEventPrimaryDirectionalMotionAxis The main movement axis (horizontal or
     *   vertical) for single-directional scrolling when using the touchpad [inputDeviceSize]. For
     *   instance, if the primary axis is set to X, a display prioritizes scrolling its content (for
     *   both horizontal and vertical containers) based on the device's X-axis movement. Note that
     *   this input axis may not correspond directly to the resulting scrolling axis on the display
     *   (e.g., X-axis movement causing vertical scrolling).
     * @param inputDeviceSize The dimensions of the external indirect pointer input device that
     *   provide the boundaries for indirect input. If you go outside these dimensions, the tests
     *   will throw an exception. Note: This is not related to the screen coordinates.
     * @param block Block of code/events to execute in indirect scope
     */
    fun indirectPointer(
        indirectPointerEventPrimaryDirectionalMotionAxis:
            IndirectPointerEventPrimaryDirectionalMotionAxis,
        inputDeviceSize: IntSize,
        block: IndirectPointerInjectionScope.() -> Unit,
    )

    /** Injects all mouse events sent by the given [block] */
    fun mouse(block: MouseInjectionScope.() -> Unit)

    /** Injects all key events sent by the given [block] */
    fun key(block: KeyInjectionScope.() -> Unit)

    /** Injects all rotary events sent by the given [block] */
    fun rotary(block: RotaryInjectionScope.() -> Unit)

    /** Injects all trackpad events sent by the given [block] */
    fun trackpad(block: TrackpadInjectionScope.() -> Unit)
}

internal class MultiModalInjectionScopeImpl(node: SemanticsNode, testContext: TestContext) :
    MultiModalInjectionScope, Density by node.layoutInfo.density {
    // TODO(b/133217292): Better error: explain which gesture couldn't be performed
    private var _semanticsNode: SemanticsNode? = node
    private val semanticsNode
        get() =
            checkNotNull(_semanticsNode) {
                "Can't query SemanticsNode, InjectionScope has already been disposed"
            }

    // TODO(b/133217292): Better error: explain which gesture couldn't be performed
    private var _inputDispatcher: InputDispatcher? =
        createInputDispatcher(
            testContext,
            checkNotNull(semanticsNode.root) { "null semantics root" },
        )
    internal val inputDispatcher
        get() =
            checkNotNull(_inputDispatcher) {
                "Can't send gesture, InjectionScope has already been disposed"
            }

    /**
     * Returns and stores the visible bounds of the [semanticsNode] we're interacting with. This
     * applies clipping, which is almost always the correct thing to do when injecting gestures, as
     * gestures operate on visible UI.
     */
    private val boundsInRoot: Rect by lazy { semanticsNode.boundsInRoot }

    /**
     * Returns the size of the visible part of the node we're interacting with. This is contrary to
     * [SemanticsNode.size], which returns the unclipped size of the node.
     */
    override val visibleSize: IntSize by lazy {
        IntSize(boundsInRoot.width.roundToInt(), boundsInRoot.height.roundToInt())
    }

    /**
     * Transforms the [position] to root coordinates.
     *
     * @param position A position in local coordinates
     * @return [position] transformed to coordinates relative to the containing root.
     */
    internal fun localToRoot(position: Offset): Offset {
        return if (position.isValid()) {
            position + boundsInRoot.topLeft
        } else {
            // Allows invalid position to still pass back through Compose (for testing)
            position
        }
    }

    internal fun rootToLocal(position: Offset): Offset {
        return if (position.isValid()) {
            position - boundsInRoot.topLeft
        } else {
            // Allows invalid position to still pass back through Compose (for testing)
            position
        }
    }

    override val viewConfiguration: ViewConfiguration
        get() = semanticsNode.layoutInfo.viewConfiguration

    internal fun dispose() {
        _semanticsNode = null
        _inputDispatcher?.also {
            _inputDispatcher = null
            try {
                it.flush()
            } finally {
                it.dispose()
            }
        }
    }

    /**
     * Adds the given [durationMillis] to the current event time, delaying the next event by that
     * time. Only valid when a gesture has already been started, or when a finished gesture is
     * resumed.
     */
    override fun advanceEventTime(durationMillis: Long) {
        inputDispatcher.advanceEventTime(durationMillis)
    }

    private val touchScope: TouchInjectionScope = TouchInjectionScopeImpl(this)

    private var indirectPointerScope: IndirectPointerInjectionScope? = null

    private val mouseScope: MouseInjectionScope = MouseInjectionScopeImpl(this)

    private val keyScope: KeyInjectionScope = KeyInjectionScopeImpl(this)

    private val rotaryScope: RotaryInjectionScope = RotaryInjectionScopeImpl(this)

    private val trackpadScope: TrackpadInjectionScope = TrackpadInjectionScopeImpl(this)

    override fun touch(block: TouchInjectionScope.() -> Unit) {
        block.invoke(touchScope)
    }

    override fun indirectPointer(
        indirectPointerEventPrimaryDirectionalMotionAxis:
            IndirectPointerEventPrimaryDirectionalMotionAxis,
        inputDeviceSize: IntSize,
        block: IndirectPointerInjectionScope.() -> Unit,
    ) {
        // A new MultiModalInjectionScopeImpl is recreated every time this block is called (see
        // [Actions.kt]), so, generally, it's unlikely these will ever be updated (though we have
        // support for it).
        if (indirectPointerScope == null) {
            indirectPointerScope =
                IndirectPointerInjectionScopeImpl(
                    this,
                    initialInputDeviceSize = inputDeviceSize,
                    initialAxis = indirectPointerEventPrimaryDirectionalMotionAxis,
                )
        } else {
            (indirectPointerScope as? IndirectPointerInjectionScopeImpl)?.updateConfiguration(
                size = inputDeviceSize,
                axis = indirectPointerEventPrimaryDirectionalMotionAxis,
            )
        }
        block.invoke(indirectPointerScope!!)
    }

    override fun mouse(block: MouseInjectionScope.() -> Unit) {
        block.invoke(mouseScope)
    }

    override fun key(block: KeyInjectionScope.() -> Unit) {
        block.invoke(keyScope)
    }

    override fun rotary(block: RotaryInjectionScope.() -> Unit) {
        block.invoke(rotaryScope)
    }

    override fun trackpad(block: TrackpadInjectionScope.() -> Unit) {
        block.invoke(trackpadScope)
    }
}
