/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was created using the `create_project.py` script located in the
 * `<AndroidX root>/development/project-creator` directory.
 *
 * Please use that script when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import androidx.build.AndroidXComposePlugin
import androidx.build.Publish
import org.jetbrains.androidx.build.JetBrainsAndroidXPlugin
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType

plugins {
    id("AndroidXPlugin")
    id("com.android.library")
    id("AndroidXComposePlugin")
    id("JetBrainsAndroidXPlugin")
}

AndroidXComposePlugin.applyAndConfigureKotlinPlugin(project)
JetBrainsAndroidXPlugin.applyAndConfigure(project)

androidXComposeMultiplatform {
    android()
    desktop()
    darwin()
    js()
    wasm()
}

kotlin {
    sourceSets {
        def navigationEventVersion = project.findProperty('artifactRedirection.version.androidx.navigationevent')
        commonMain {
            dependencies {
                api("androidx.navigationevent:navigationevent:$navigationEventVersion")
                api(project(":compose:runtime:runtime"))
                implementation(project(":compose:ui:ui"))
                implementation(libs.kotlinStdlib)
                implementation(libs.kotlinCoroutinesCore)
            }
        }

        commonTest {
            dependencies {
                implementation(libs.kotlinTest)
                api("androidx.navigationevent:navigationevent-testing:$navigationEventVersion")
                implementation(project(":kruth:kruth"))
            }
        }

        jvmMain {
            dependsOn(commonMain)
            dependencies {
            }
        }

        androidMain {
            dependsOn(jvmMain)
            dependencies {
            }
        }

        jvmTest {
            dependsOn(commonTest)
            dependencies {
            }
        }

        androidUnitTest {
            dependsOn(jvmTest)
        }

        androidInstrumentedTest {
            dependsOn(jvmTest)
            dependencies {
                implementation("androidx.compose.material:material:1.9.0-rc01")
                implementation("androidx.compose.ui:ui-test:1.9.0-rc01")
                implementation("androidx.compose.ui:ui-test-junit4:1.9.0-rc01")
                implementation("androidx.compose.ui:ui-test-manifest:1.9.0-rc01")
                implementation(libs.testExtJunit)
                implementation(libs.testCore)
                implementation(libs.testRunner)
                implementation(libs.testRules)
            }
        }

        nonAndroidMain.dependsOn(commonMain)
        nonAndroidTest.dependsOn(commonTest)
        nonJvmMain.dependsOn(nonAndroidMain)
        nonJvmTest.dependsOn(nonAndroidTest)

        desktopMain {
            dependsOn(jvmMain)
            dependsOn(nonAndroidMain)
        }

        desktopTest {
            dependsOn(jvmTest)
            dependsOn(nonAndroidTest)
        }

        nativeMain.dependsOn(nonJvmMain)
        nativeTest.dependsOn(nonJvmTest)

        webMain.dependsOn(nonJvmMain)
        webTest.dependsOn(nonJvmTest)

        targets.all { target ->
            if (target.platformType == KotlinPlatformType.native) {
                target.compilations["main"].defaultSourceSet.dependsOn(nativeMain)
                target.compilations["test"].defaultSourceSet.dependsOn(nativeTest)
            } else if (target.platformType in [KotlinPlatformType.js, KotlinPlatformType.wasm]) {
                target.compilations["main"].defaultSourceSet.dependsOn(webMain)
                target.compilations["test"].defaultSourceSet.dependsOn(webTest)
            }
        }
    }
}

androidx {
    name = "NavigationEvent Compose"
    publish = Publish.SNAPSHOT_AND_RELEASE
    inceptionYear = "2025"
    description = "Compose integration with NavigationEvent"
}

android {
    namespace = "androidx.navigationevent.compose"
}
