package com.testdata

import androidx.appfunctions.`internal`.AppFunctionInventory
import androidx.appfunctions.metadata.AppFunctionMetadata
import androidx.appfunctions.metadata.AppFunctionSchemaMetadata
import javax.`annotation`.processing.Generated
import kotlin.String
import kotlin.collections.Map

/**
 * Source Files:
 * AllPrimitiveInputFunctions.....kt
 */
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$AllPrimitiveInputFunctions_AppFunctionInventory` : AppFunctionInventory {
  override val functionIdToMetadataMap: Map<String, AppFunctionMetadata> = mapOf()

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONINT_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONLONG_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONFLOAT_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONDOUBLE_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONBOOLEAN_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONSTRING_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEINT_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLELONG_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEFLOAT_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEDOUBLE_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEBOOLEAN_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLESTRING_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONINTARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONLONGARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONFLOATARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONDOUBLEARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONBOOLEANARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONSTRINGLIST_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEINTARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLELONGARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEFLOATARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEDOUBLEARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLEBOOLEANARRAY_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_ALLPRIMITIVEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLESTRINGLIST_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null
}
