package com.testdata

import androidx.appfunctions.`internal`.AppFunctionInventory
import androidx.appfunctions.metadata.AppFunctionMetadata
import androidx.appfunctions.metadata.AppFunctionSchemaMetadata
import javax.`annotation`.processing.Generated
import kotlin.String
import kotlin.collections.Map

/**
 * Source Files:
 * FakeAllPrimitiveParamsImpl.....kt
 * FakeSchemas.....kt
 */
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$FakeAllPrimitiveParamsImpl_AppFunctionInventory` : AppFunctionInventory {
  override val functionIdToMetadataMap: Map<String, AppFunctionMetadata> = mapOf()

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = AppFunctionSchemaMetadata(category= "fake_schema_category",
      name="allPrimitiveParams", version=1)

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = AppFunctionSchemaMetadata(category= "fake_schema_category",
      name="allPrimitiveParams", version=1)
}
