package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "SCHEMA_DEFINITION",
  componentNames = [
    "com.testdata.FakeAllNullablePrimitiveParamsWithDefaultValues",
    "com.testdata.FakeAllPrimitiveParams",
    "com.testdata.FakeAllPrimitiveReturns",
    "com.testdata.FakeNoArg",
    "com.testdata.ShowNoteFunction",
    "com.testdata.UpdateNoteFunction",
    "com.testdata.diffPackageSchemas.DiffPackageInputSchemas",
    "com.testdata.diffPackageSchemas.DiffPackageOutputSchemas",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$Main_SchemaDefinitionComponentRegistry`
