package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "INVOKER",
  componentNames = [
    "com.testdata.${'$'}AllPrimitiveInputFunctions_AppFunctionInvoker",
    "com.testdata.${'$'}SimpleFunction_AppFunctionInvoker",
    "com.testdata.diff.${'$'}SimpleFunction_AppFunctionInvoker",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$Main_InvokerComponentRegistry`
