package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "FUNCTION",
  componentNames = [
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionBoolean",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionBooleanArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionDouble",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionDoubleArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionFloat",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionFloatArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionInt",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionIntArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionLong",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionLongArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableBoolean",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableBooleanArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableDouble",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableDoubleArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableFloat",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableFloatArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableInt",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableIntArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableLong",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableLongArray",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableString",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionNullableStringList",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionString",
    "com.testdata.AllPrimitiveInputFunctions.simpleFunctionStringList",
    "com.testdata.SimpleFunction.simpleFunction",
    "com.testdata.diff.SimpleFunction.simpleFunction",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$Main_FunctionComponentRegistry`
