package com.testdata

import androidx.appfunctions.`internal`.AppFunctionInventory
import androidx.appfunctions.metadata.AppFunctionMetadata
import androidx.appfunctions.metadata.AppFunctionSchemaMetadata
import javax.`annotation`.processing.Generated
import kotlin.String
import kotlin.collections.Map

/**
 * Source Files:
 * SerializableInputFunctions.....kt
 */
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$SerializableInputFunctions_AppFunctionInventory` : AppFunctionInventory {
  override val functionIdToMetadataMap: Map<String, AppFunctionMetadata> = mapOf()

  private val COM_TESTDATA_SERIALIZABLEINPUTFUNCTIONS_SIMPLEFUNCTION_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_SERIALIZABLEINPUTFUNCTIONS_SIMPLEFUNCTIONSERIALIZABLELIST_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_SERIALIZABLEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLESERIALIZABLELIST_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null

  private
      val COM_TESTDATA_SERIALIZABLEINPUTFUNCTIONS_SIMPLEFUNCTIONNULLABLESERIALIZABLE_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = null
}
