package com.testdata

import androidx.appfunctions.`internal`.AppFunctionInventory
import androidx.appfunctions.metadata.AppFunctionMetadata
import androidx.appfunctions.metadata.AppFunctionSchemaMetadata
import javax.`annotation`.processing.Generated
import kotlin.String
import kotlin.collections.Map

/**
 * Source Files:
 * SimpleFunction.....kt
 */
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$SimpleFunction_AppFunctionInventory` : AppFunctionInventory {
  override val functionIdToMetadataMap: Map<String, AppFunctionMetadata> = mapOf()

  private val COM_TESTDATA_SIMPLEFUNCTION_SIMPLEFUNCTION_SCHEMA_METADATA: AppFunctionSchemaMetadata?
      = null
}
