/*
 * Copyright 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import androidx.build.AndroidXComposePlugin
import androidx.build.Publish
import org.jetbrains.androidx.build.JetBrainsAndroidXPlugin
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType

plugins {
    id("AndroidXPlugin")
    id("com.android.library")
    id("AndroidXComposePlugin")
    alias(libs.plugins.kotlinSerialization)
    id("JetBrainsAndroidXPlugin")
}

AndroidXComposePlugin.applyAndConfigureKotlinPlugin(project)
JetBrainsAndroidXPlugin.applyAndConfigure(project)

androidXComposeMultiplatform {
    android()
    desktop()
    darwin()
    js()
    wasm()
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(libs.kotlinStdlib)
                implementation(libs.kotlinStdlib)
                implementation(libs.kotlinSerializationCore)
                implementation("androidx.annotation:annotation:1.9.1")
                implementation("androidx.collection:collection:1.5.0")

                api(project(":navigation:navigation-runtime"))
                api(project(":navigation:navigation-common"))
                api "org.jetbrains.compose.animation:animation:1.8.2"
                api "org.jetbrains.compose.runtime:runtime:1.8.2"
                api "org.jetbrains.compose.runtime:runtime-saveable:1.8.2"

                implementation "org.jetbrains.compose.animation:animation-core:1.8.2"
                implementation "org.jetbrains.compose.foundation:foundation-layout:1.8.2"
                implementation(project(":lifecycle:lifecycle-common"))
                implementation(project(":lifecycle:lifecycle-runtime-compose"))
                implementation(project(":lifecycle:lifecycle-viewmodel"))
                implementation(project(":lifecycle:lifecycle-viewmodel-compose"))
                implementation(project(":lifecycle:lifecycle-viewmodel-savedstate"))
                implementation project(":savedstate:savedstate")
                implementation project(":savedstate:savedstate-compose")
            }
        }

        commonTest {
            dependencies {
                implementation(libs.kotlinStdlib)
                implementation(libs.kotlinCoroutinesTest)
                implementation(libs.kotlinTest)
                implementation(project(":compose:material:material"))
                implementation(project(":navigation:navigation-testing"))
                implementation(project(":internal-testutils-navigation"))
                implementation(project(":kruth:kruth"))
                implementation(project(":compose:ui:ui-test"))
            }
        }

        androidMain {
            dependsOn(commonMain)
            dependencies {
                api("androidx.activity:activity-compose:1.8.0")
            }
        }

        androidInstrumentedTest {
            dependsOn(commonTest)
            dependencies {
                implementation(project(":compose:material:material"))
                implementation project(":compose:test-utils")
                implementation project(":compose:ui:ui-tooling")
                implementation(project(":navigation:navigation-testing"))
                implementation(project(":internal-testutils-navigation"))
                implementation(project(":compose:ui:ui-test-junit4"))
                implementation("androidx.lifecycle:lifecycle-livedata-core:2.8.4")
                implementation("androidx.activity:activity-ktx:1.8.2")
                implementation("androidx.collection:collection-ktx:1.1.0")
                implementation(libs.testRunner)
                implementation(libs.junit)
                implementation(libs.truth)
            }
        }


        nonAndroidMain {
            dependsOn(commonMain)
            dependencies {
                implementation project(":compose:ui:ui-backhandler")
            }
        }
        nonAndroidTest.dependsOn(commonTest)

        desktopMain {
            dependsOn(jvmMain)
            dependsOn(nonAndroidMain)
        }
        desktopTest {
            dependsOn(jvmTest)
            dependsOn(nonAndroidTest)
            dependencies {
                implementation(libs.skikoCurrentOs)
                implementation(libs.kotlinCoroutinesSwing)
            }
        }
        nonJvmMain.dependsOn(nonAndroidMain)
        nativeMain.dependsOn(nonJvmMain)
        webMain.dependsOn(nonJvmMain)
        darwinMain.dependsOn(nativeMain)
        linuxMain.dependsOn(nativeMain)

        nonJvmTest.dependsOn(nonAndroidTest)
        nativeTest.dependsOn(nonJvmTest)
        webTest.dependsOn(nonJvmTest)
        darwinTest.dependsOn(nativeTest)
        linuxTest.dependsOn(nativeTest)

        iosMain {
            kotlin.srcDir("src/uikitMain/kotlin")
        }

        targets.all { target ->
            if (target.platformType == KotlinPlatformType.native) {
                if (target.konanTarget.family.appleFamily) {
                    target.compilations["main"].defaultSourceSet.dependsOn(darwinMain)
                    target.compilations["test"].defaultSourceSet.dependsOn(darwinTest)
                } else if (target.konanTarget.family == org.jetbrains.kotlin.konan.target.Family.LINUX) {
                    target.compilations["main"].defaultSourceSet.dependsOn(linuxMain)
                    target.compilations["test"].defaultSourceSet.dependsOn(linuxTest)
                }
            } else if (target.platformType in [KotlinPlatformType.js, KotlinPlatformType.wasm]) {
                target.compilations["main"].defaultSourceSet.dependsOn(webMain)
                target.compilations["test"].defaultSourceSet.dependsOn(webTest)
            }
        }
    }
}

androidx {
    name = "Compose Navigation"
    publish = Publish.SNAPSHOT_AND_RELEASE
    inceptionYear = "2020"
    description = "Compose integration with Navigation"
}

android {
    sourceSets.androidTest.assets.srcDirs +=
            project.rootDir.absolutePath + "/../../golden/navigation/navigation-compose"

    namespace "androidx.navigation.compose"
}
