/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.sqlite.driver.test

/**
 * Gets the compiled native library filename of the test SQLite extension (sqlite_extension.cpp).
 *
 * The expect implementation of this function for native hos tests (Linux and Mac) is generated by
 * Gradle (see GenerateLoadableExtensionSource.groovy), therefore if the definition of it changes,
 * so must the generator task.
 */
expect fun getExtensionFileName(): String
