/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package androidx.glance.appwidget.components

import android.os.Build
import androidx.annotation.DimenRes
import androidx.annotation.DrawableRes
import androidx.annotation.RestrictTo
import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.glance.Button
import androidx.glance.ButtonColors
import androidx.glance.ButtonDefaults
import androidx.glance.Emittable
import androidx.glance.EmittableWithText
import androidx.glance.GlanceModifier
import androidx.glance.GlanceNode
import androidx.glance.GlanceTheme
import androidx.glance.ImageProvider
import androidx.glance.action.Action
import androidx.glance.action.NoRippleOverride
import androidx.glance.action.action
import androidx.glance.action.clickable
import androidx.glance.appwidget.R
import androidx.glance.appwidget.isAtLeastApi31
import androidx.glance.semantics.contentDescription
import androidx.glance.semantics.semantics
import androidx.glance.unit.ColorProvider

/**
 * A button styled per Material3. It has a filled background. It is more opinionated than [Button]
 * and suitable for uses where M3 is preferred.
 *
 * @param text The text that this button will show.
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param icon An optional leading icon placed before the text.
 * @param colors The colors to use for the background and content of the button.
 * @param maxLines An optional maximum number of lines for the text to span, wrapping if necessary.
 *   If the text exceeds the given number of lines, it will be truncated.
 * @param key A stable and unique key that identifies the action for this button. This ensures that
 *   the correct action is triggered, especially in cases of items that change order. If not
 *   provided we use the key that is automatically generated by the Compose runtime, which is unique
 *   for every exact code location in the composition tree.
 */
@Composable
public fun FilledButton(
    text: String,
    onClick: () -> Unit,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    icon: ImageProvider? = null,
    colors: ButtonColors = ButtonDefaults.buttonColors(),
    maxLines: Int = Int.MAX_VALUE,
    key: String? = null,
): Unit =
    FilledButton(
        text = text,
        onClick = action(block = onClick, key = key),
        modifier = modifier,
        enabled = enabled,
        icon = icon,
        colors = colors,
        maxLines = maxLines,
    )

/**
 * A button styled per Material3. It has a filled background. It is more opinionated than [Button]
 * and suitable for uses where M3 is preferred.
 *
 * @param text The text that this button will show.
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param icon An optional leading icon placed before the text.
 * @param colors The colors to use for the background and content of the button.
 * @param maxLines An optional maximum number of lines for the text to span, wrapping if necessary.
 *   If the text exceeds the given number of lines, it will be truncated.
 */
@Composable
public fun FilledButton(
    text: String,
    onClick: Action,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    icon: ImageProvider? = null,
    colors: ButtonColors = ButtonDefaults.buttonColors(),
    maxLines: Int = Int.MAX_VALUE,
): Unit =
    M3TextButtonElement(
        text = text,
        modifier = modifier,
        enabled = enabled,
        icon = icon,
        contentColor = colors.contentColor,
        backgroundTint = colors.backgroundColor,
        backgroundResource = R.drawable.glance_component_btn_filled,
        onClick = onClick,
        maxLines = maxLines,
    )

/**
 * An outline button styled per Material3. It has a transparent background. It is more opinionated
 * than [Button] and suitable for uses where M3 is preferred.
 *
 * @param text The text that this button will show.
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param icon An optional leading icon placed before the text.
 * @param contentColor The color used for the text, optional icon tint, and outline.
 * @param maxLines An optional maximum number of lines for the text to span, wrapping if necessary.
 *   If the text exceeds the given number of lines, it will be truncated.
 * @param key A stable and unique key that identifies the action for this button. This ensures that
 *   the correct action is triggered, especially in cases of items that change order. If not
 *   provided we use the key that is automatically generated by the Compose runtime, which is unique
 *   for every exact code location in the composition tree.
 */
@Composable
public fun OutlineButton(
    text: String,
    contentColor: ColorProvider,
    onClick: () -> Unit,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    icon: ImageProvider? = null,
    maxLines: Int = Int.MAX_VALUE,
    key: String? = null,
): Unit =
    OutlineButton(
        text = text,
        contentColor = contentColor,
        onClick = action(block = onClick, key = key),
        modifier = modifier,
        enabled = enabled,
        icon = icon,
        maxLines = maxLines,
    )

/**
 * An outline button styled per Material3. It has a transparent background. It is more opinionated
 * than [Button] and suitable for uses where M3 is preferred.
 *
 * @param text The text that this button will show.
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param icon An optional leading icon placed before the text.
 * @param contentColor The color used for the text, optional icon tint, and outline.
 * @param maxLines An optional maximum number of lines for the text to span, wrapping if necessary.
 *   If the text exceeds the given number of lines, it will be truncated.
 */
@Composable
public fun OutlineButton(
    text: String,
    contentColor: ColorProvider,
    onClick: Action,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    icon: ImageProvider? = null,
    maxLines: Int = Int.MAX_VALUE,
) {
    val bg: ColorProvider = contentColor
    val fg: ColorProvider = contentColor

    M3TextButtonElement(
        text = text,
        onClick = onClick,
        modifier = modifier,
        enabled = enabled,
        icon = icon,
        contentColor = fg,
        backgroundResource = R.drawable.glance_component_btn_outline,
        backgroundTint = bg,
        maxLines = maxLines,
        isOutlineButton = true,
    )
}

/**
 * Intended to fill the role of primary icon button or fab.
 *
 * @param imageProvider the icon to be drawn in the button
 * @param contentDescription Text used by accessibility services to describe what this image
 *   represents. This text should be localized, such as by using
 *   androidx.compose.ui.res.stringResource or similar
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param backgroundColor The color to tint the button's background.
 * @param contentColor The color to tint the button's icon.
 * @param key A stable and unique key that identifies the action for this button. This ensures that
 *   the correct action is triggered, especially in cases of items that change order. If not
 *   provided we use the key that is automatically generated by the Compose runtime, which is unique
 *   for every exact code location in the composition tree.
 */
@Composable
public fun SquareIconButton(
    imageProvider: ImageProvider,
    contentDescription: String?,
    onClick: () -> Unit,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    backgroundColor: ColorProvider = GlanceTheme.colors.primary,
    contentColor: ColorProvider = GlanceTheme.colors.onPrimary,
    key: String? = null,
): Unit =
    SquareIconButton(
        imageProvider = imageProvider,
        contentDescription = contentDescription,
        onClick = action(block = onClick, key = key),
        modifier = modifier,
        enabled = enabled,
        backgroundColor = backgroundColor,
        contentColor = contentColor,
    )

/**
 * Intended to fill the role of primary icon button or fab.
 *
 * @param imageProvider the icon to be drawn in the button
 * @param contentDescription Text used by accessibility services to describe what this image
 *   represents. This text should be localized, such as by using
 *   androidx.compose.ui.res.stringResource or similar
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param backgroundColor The color to tint the button's background.
 * @param contentColor The color to tint the button's icon.
 */
@Composable
public fun SquareIconButton(
    imageProvider: ImageProvider,
    contentDescription: String?,
    onClick: Action,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    backgroundColor: ColorProvider = GlanceTheme.colors.primary,
    contentColor: ColorProvider = GlanceTheme.colors.onPrimary,
): Unit =
    M3IconButtonElement(
        imageProvider = imageProvider,
        contentDescription = contentDescription,
        backgroundColor = backgroundColor,
        contentColor = contentColor,
        shape = IconButtonShape.Square,
        modifier = modifier,
        enabled = enabled,
        onClick = onClick,
    )

/**
 * Intended to fill the role of secondary icon button. Background color may be null to have the
 * button display as an icon with a 48x48dp hit area.
 *
 * @param imageProvider the icon to be drawn in the button
 * @param contentDescription Text used by accessibility services to describe what this image
 *   represents. This text should be localized, such as by using
 *   androidx.compose.ui.res.stringResource or similar
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param backgroundColor The color to tint the button's background. May be null to make background
 *   transparent.
 * @param contentColor The color to tint the button's icon.
 * @param key A stable and unique key that identifies the action for this button. This ensures that
 *   the correct action is triggered, especially in cases of items that change order. If not
 *   provided we use the key that is automatically generated by the Compose runtime, which is unique
 *   for every exact code location in the composition tree.
 */
@Composable
public fun CircleIconButton(
    imageProvider: ImageProvider,
    contentDescription: String?,
    onClick: () -> Unit,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    backgroundColor: ColorProvider? = GlanceTheme.colors.background,
    contentColor: ColorProvider = GlanceTheme.colors.onSurface,
    key: String? = null,
): Unit =
    CircleIconButton(
        imageProvider = imageProvider,
        contentDescription = contentDescription,
        backgroundColor = backgroundColor,
        contentColor = contentColor,
        modifier = modifier,
        enabled = enabled,
        onClick = action(block = onClick, key = key),
    )

/**
 * Intended to fill the role of secondary icon button. Background color may be null to have the
 * button display as an icon with a 48x48dp hit area.
 *
 * @param imageProvider the icon to be drawn in the button
 * @param contentDescription Text used by accessibility services to describe what this image
 *   represents. This text should be localized, such as by using
 *   androidx.compose.ui.res.stringResource or similar
 * @param onClick The action to be performed when this button is clicked.
 * @param modifier The modifier to be applied to this button.
 * @param enabled If false, the button will not be clickable.
 * @param backgroundColor The color to tint the button's background. May be null to make background
 *   transparent.
 * @param contentColor The color to tint the button's icon.
 */
@Composable
public fun CircleIconButton(
    imageProvider: ImageProvider,
    contentDescription: String?,
    onClick: Action,
    modifier: GlanceModifier = GlanceModifier,
    enabled: Boolean = true,
    backgroundColor: ColorProvider? = GlanceTheme.colors.background,
    contentColor: ColorProvider = GlanceTheme.colors.onSurface,
): Unit =
    M3IconButtonElement(
        imageProvider = imageProvider,
        contentDescription = contentDescription,
        backgroundColor = backgroundColor,
        contentColor = contentColor,
        shape = IconButtonShape.Circle,
        modifier = modifier,
        enabled = enabled,
        onClick = onClick,
    )

@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public enum class IconButtonShape(
    @DrawableRes public val shape: Int,
    @DimenRes public val cornerRadius: Int,
    @DrawableRes public val ripple: Int,
    public val defaultSize: Dp,
) {
    Square(
        R.drawable.glance_component_btn_square,
        R.dimen.glance_component_square_icon_button_corners,
        ripple =
            if (isAtLeastApi31) NoRippleOverride
            else R.drawable.glance_component_square_button_ripple,
        defaultSize = 60.dp,
    ),
    Circle(
        R.drawable.glance_component_btn_circle,
        R.dimen.glance_component_circle_icon_button_corners,
        ripple =
            if (isAtLeastApi31) NoRippleOverride
            else R.drawable.glance_component_circle_button_ripple,
        defaultSize = 48.dp,
    ),
}

/**
 * This is a placeholder emittable. If [androidx.glance.Backend] is RemoteViews, it will be turned
 * into a tree of emittables during the normalize step.
 */
@Composable
private fun M3IconButtonElement(
    imageProvider: ImageProvider,
    contentDescription: String?,
    contentColor: ColorProvider,
    backgroundColor: ColorProvider?,
    shape: IconButtonShape,
    onClick: Action,
    modifier: GlanceModifier,
    enabled: Boolean,
) {
    var finalModifier =
        if (enabled)
            modifier.clickable(
                onClick = onClick,
                rippleOverride =
                    if (isAtLeastApi31) NoRippleOverride
                    else R.drawable.glance_component_m3_button_ripple,
            )
        else modifier

    finalModifier =
        if (contentDescription != null) {
            finalModifier.semantics { this.contentDescription = contentDescription }
        } else {
            finalModifier
        }

    GlanceNode(
        factory = ::EmittableM3IconButton,
        update = {
            this.set(imageProvider) { this.imageProvider = it }
            this.set(contentColor) { this.contentColor = it }
            this.set(backgroundColor) { this.backgroundColor = it }
            this.set(shape) { this.shape = it }
            this.set(finalModifier) { this.modifier = it }
            this.set(enabled) { this.enabled = it }
        },
    )
}

@Composable
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
private fun M3TextButtonElement(
    text: String,
    onClick: Action,
    modifier: GlanceModifier,
    enabled: Boolean = true,
    icon: ImageProvider?,
    contentColor: ColorProvider,
    backgroundResource: Int,
    backgroundTint: ColorProvider,
    maxLines: Int,
    isOutlineButton: Boolean = false, // used for remote compose
) {
    val finalModifier =
        if (enabled)
            modifier.clickable(
                onClick = onClick,
                rippleOverride =
                    if (isAtLeastApi31) NoRippleOverride
                    else R.drawable.glance_component_m3_button_ripple,
            )
        else modifier

    GlanceNode(
        factory = ::EmittableM3TextButton,
        update = {
            this.set(text) { this.text = it }
            this.set(finalModifier) { this.modifier = it }
            this.set(enabled) { this.enabled = it }
            this.set(icon) { this.icon = it }
            this.set(contentColor) { this.contentColor = it }
            this.set(backgroundResource) { this.backgroundResource = it }
            this.set(backgroundTint) { this.backgroundTint = it }
            this.set(maxLines) { this.maxLines = it }
            this.set(isOutlineButton) { this.isOutlineButton = it }
        },
    )
}

@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public class EmittableM3TextButton
private constructor(
    public override var text: String,
    public override var modifier: GlanceModifier,
    public var enabled: Boolean = true,
    public var icon: ImageProvider?,
    public var contentColor: ColorProvider,
    public @DrawableRes var backgroundResource: Int,
    public var backgroundTint: ColorProvider,
    public override var maxLines: Int,
    public var isOutlineButton: Boolean,
) : EmittableWithText() {

    /** No-arg constructor for when its constructed as a [GlanceNode] */
    public constructor() :
        this(
            text = "",
            modifier = GlanceModifier,
            enabled = false,
            icon = null,
            contentColor = ColorProvider(androidx.compose.ui.graphics.Color.Transparent),
            backgroundResource = 0,
            backgroundTint = ColorProvider(androidx.compose.ui.graphics.Color.Transparent),
            maxLines = -1,
            isOutlineButton = false,
        )

    override fun copy(): Emittable {
        return EmittableM3TextButton(
            text = text,
            modifier = modifier,
            enabled = enabled,
            icon = icon,
            contentColor = contentColor,
            backgroundResource = backgroundResource,
            backgroundTint = backgroundTint,
            maxLines = maxLines,
            isOutlineButton = isOutlineButton,
        )
    }
}

@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public class EmittableM3IconButton
private constructor(
    public var imageProvider: ImageProvider?,
    public var contentColor: ColorProvider?,
    public var backgroundColor: ColorProvider?,
    public var shape: IconButtonShape,
    public override var modifier: GlanceModifier,
    public var enabled: Boolean,
) : Emittable {

    public constructor() :
        this(
            imageProvider = null,
            contentColor = null,
            backgroundColor = null,
            shape = IconButtonShape.Circle,
            modifier = GlanceModifier,
            enabled = false,
        )

    override fun copy(): Emittable {
        return EmittableM3IconButton(
            imageProvider = imageProvider,
            contentColor = contentColor,
            backgroundColor = backgroundColor,
            shape = shape,
            modifier = modifier,
            enabled = enabled,
        )
    }
}

private val isAtLeastApi31
    get() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.S
