package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "SCHEMA_DEFINITION",
  componentNames = [
    "com.testdata.BooleanArrayReturn",
    "com.testdata.BooleanReturn",
    "com.testdata.ByteArrayReturn",
    "com.testdata.DoubleArrayReturn",
    "com.testdata.DoubleReturn",
    "com.testdata.FakeAllNullablePrimitiveArrayParamsWithDefaultValues",
    "com.testdata.FakeAllNullablePrimitiveParamsWithDefaultValues",
    "com.testdata.FakeAllPrimitiveArrayParams",
    "com.testdata.FakeAllPrimitiveParams",
    "com.testdata.FakeNoArg",
    "com.testdata.FloatArrayReturn",
    "com.testdata.FloatReturn",
    "com.testdata.IntArrayReturn",
    "com.testdata.IntReturn",
    "com.testdata.LongArrayReturn",
    "com.testdata.LongReturn",
    "com.testdata.NullableBooleanArrayReturn",
    "com.testdata.NullableBooleanReturn",
    "com.testdata.NullableByteArrayReturn",
    "com.testdata.NullableDoubleArrayReturn",
    "com.testdata.NullableDoubleReturn",
    "com.testdata.NullableFloatArrayReturn",
    "com.testdata.NullableFloatReturn",
    "com.testdata.NullableIntArrayReturn",
    "com.testdata.NullableIntReturn",
    "com.testdata.NullableLongArrayReturn",
    "com.testdata.NullableLongReturn",
    "com.testdata.NullableStringItemListReturn",
    "com.testdata.NullableStringListReturn",
    "com.testdata.NullableStringReturn",
    "com.testdata.StringListReturn",
    "com.testdata.StringReturn",
    "com.testdata.UnitReturn",
    "com.testdata.diffPackageSchemas.DiffPackageInputSchemas",
    "com.testdata.diffPackageSchemas.DiffPackageOutputSchemas",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$Main_SchemaDefinitionComponentRegistry`
