/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package androidx.car.app.dialer;

import android.annotation.SuppressLint;

import androidx.car.app.annotations.ExperimentalCarApi;
import androidx.car.app.dialer.TelephoneKeypadTemplate.KeypadKey;

/** Callbacks generated by the {@link TelephoneKeypadTemplate}. */
@ExperimentalCarApi
public interface TelephoneKeypadCallback {
    /**
     * Called when a key is pressed and held. The length of time between key down and this event is
     * determined by the host and always fires in the following order:
     *
     * <ol>
     *   <li>Key down</li>
     *   <li>Key long press</li>
     *   <li>Key up</li>
     * </ol>
     *
     * This event provides the {@code key} that was pressed in the form of an int constant defined
     * in the {@link TelephoneKeypadTemplate} object prefixed with `KEY_`.
     */
    @SuppressLint("ExecutorRegistration")
    void onKeyLongPress(@KeypadKey int key);

    /**
     * Called when a key is pushed. This is only called once for each user interaction, even if the
     * key is held down (eg. does not repeat the same event call for a single key push).
     *
     * <p>This event provides the {@code key} that was pressed in the form of an int constant
     * defined in the {@link TelephoneKeypadTemplate} object prefixed with `KEY_`.
     */
    @SuppressLint("ExecutorRegistration")
    void onKeyDown(@KeypadKey int key);

    /**
     * Called when a key is released. This is only called once for each user interaction.
     *
     * <p>This event provides the {@code key} that was pressed in the form of an int constant
     * defined in the {@link TelephoneKeypadTemplate} object prefixed with `KEY_`.
     */
    @SuppressLint("ExecutorRegistration")
    void onKeyUp(@KeypadKey int key);
}

