/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.room3

/**
 * Marks a property in an [Entity] as the primary key.
 *
 * If you would like to define a composite primary key, you should use [Entity.primaryKeys]
 * function.
 *
 * Each [Entity] must declare a primary key unless one of its super classes declares a primary key.
 * If both an [Entity] and its super class defines a [PrimaryKey], the child's [PrimaryKey]
 * definition will override the parent's [PrimaryKey].
 *
 * If this annotation is used on a [Embedded] property, all columns inherited from that embedded
 * property becomes the composite primary key (including its grand children properties).
 */
@Target(AnnotationTarget.FIELD, AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
public annotation class PrimaryKey(
    /**
     * Set to true to let SQLite generate the unique id.
     *
     * When set to `true`, the SQLite type affinity for the property should be `INTEGER`.
     *
     * If the property type is [Long] or [Int] (or its [TypeConverter] converts it to a `Long` or
     * `Int`), [Insert] functions treat `0` as not-set while inserting the item. Similarly, if the
     * property type is nullable (`Long?` or `Int?`), [Insert] functions treat `null` as not-set
     * while inserting the item.
     *
     * The strategy on how the id will be generated will be based on the [algorithm] property.
     *
     * @return Whether the primary key should be auto-generated by SQLite or not. Defaults to false.
     * @see algorithm
     */
    val autoGenerate: Boolean = false,

    /**
     * When [autoGenerate] is set to `true` then the algorithm used to auto-generate primary keys
     * can be configured through this property. When [autoGenerate] is set to `false` this value is
     * ignored.
     *
     * For details, see the [auto increment documentation](https://sqlite.org/autoinc.html).
     *
     * @return The algorithm to use for auto-generation. Defaults to [Algorithm.AUTOINCREMENT].
     * @see autoGenerate
     */
    val algorithm: Algorithm = Algorithm.AUTOINCREMENT,
) {
    /** The [PrimaryKey] auto-generate algorithms. */
    public enum class Algorithm {
        /** The [PrimaryKey] auto-generate algorithm that will reuse ids. */
        ROWID,

        /**
         * The [PrimaryKey] auto-generate algorithm that will never reuse ids over the lifetime of
         * the database file. This algorithm is not as performant as [ROWID] in order to guarantee
         * uniqueness and should be avoided unless strictly needed.
         */
        AUTOINCREMENT,
    }
}
