/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

import androidx.annotation.IntDef
import androidx.annotation.RestrictTo
import kotlin.annotation.AnnotationRetention
import kotlin.annotation.Retention
import kotlin.annotation.Target
import kotlin.jvm.JvmStatic

public class ColorSpaceTransferDawn private constructor() {

    public companion object {
        public const val Identity: Int = 0x00000001
        public const val SRGB: Int = 0x00000002
        public const val DisplayP3: Int = 0x00000003
        public const val SMPTE_170M: Int = 0x00000004
        public const val HLG: Int = 0x00000005
        public const val PQ: Int = 0x00000006
        public const val BT_1886: Int = 0x00000007
        internal val names: Map<Int, String> =
            mapOf(
                0x00000001 to "Identity",
                0x00000002 to "SRGB",
                0x00000003 to "DisplayP3",
                0x00000004 to "SMPTE_170M",
                0x00000005 to "HLG",
                0x00000006 to "PQ",
                0x00000007 to "BT_1886",
            )

        @JvmStatic public fun toString(@Type value: Int): String = names[value] ?: value.toString()
    }

    @Retention(AnnotationRetention.SOURCE)
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    @IntDef(
        value =
            [
                Identity,
                SRGB,
                DisplayP3,
                SMPTE_170M,
                HLG,
                PQ,
                BT_1886,
            ]
    )
    @Target(
        AnnotationTarget.FUNCTION,
        AnnotationTarget.TYPE,
        AnnotationTarget.VALUE_PARAMETER,
        AnnotationTarget.PROPERTY,
    )
    public annotation class Type
}
