/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

public fun interface DeviceLostCallback {
    /**
     * A callback function for handling device loss events.
     *
     * @param device A pointer to the device that was lost.
     * @param reason The reason for the device loss.
     * @param message An optional message providing more details on the device loss.
     */
    @Suppress("INAPPLICABLE_JVM_NAME")
    @JvmName("onDeviceLost")
    public fun onDeviceLost(device: GPUDevice, @DeviceLostReason reason: Int, message: String)
}

internal class DeviceLostCallbackRunnable(
    private val callback: DeviceLostCallback,
    private val device: GPUDevice,
    private val reason: Int,
    private val message: String,
) : Runnable {
    override fun run() {
        callback.onDeviceLost(device, reason, message)
    }
}
