/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

import androidx.annotation.IntDef
import androidx.annotation.RestrictTo
import kotlin.annotation.AnnotationRetention
import kotlin.annotation.Retention
import kotlin.annotation.Target

@Retention(AnnotationRetention.SOURCE)
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
@IntDef(
    value =
        [
            FeatureName.CoreFeaturesAndLimits,
            FeatureName.DepthClipControl,
            FeatureName.Depth32FloatStencil8,
            FeatureName.TextureCompressionBC,
            FeatureName.TextureCompressionBCSliced3D,
            FeatureName.TextureCompressionETC2,
            FeatureName.TextureCompressionASTC,
            FeatureName.TextureCompressionASTCSliced3D,
            FeatureName.TimestampQuery,
            FeatureName.IndirectFirstInstance,
            FeatureName.ShaderF16,
            FeatureName.RG11B10UfloatRenderable,
            FeatureName.BGRA8UnormStorage,
            FeatureName.Float32Filterable,
            FeatureName.Float32Blendable,
            FeatureName.ClipDistances,
            FeatureName.DualSourceBlending,
            FeatureName.Subgroups,
            FeatureName.TextureFormatsTier1,
            FeatureName.TextureFormatsTier2,
            FeatureName.PrimitiveIndex,
            FeatureName.TextureComponentSwizzle,
        ]
)
@Target(
    AnnotationTarget.FUNCTION,
    AnnotationTarget.TYPE,
    AnnotationTarget.VALUE_PARAMETER,
    AnnotationTarget.PROPERTY,
)

/** An enumeration of optional features that a device may support. */
public annotation class FeatureName {
    public companion object {

        /** Represents the baseline set of WebGPU features and limits. */
        public const val CoreFeaturesAndLimits: Int = 0x00000001

        /** Allows disabling depth clipping. */
        public const val DepthClipControl: Int = 0x00000002

        /** Support for @see [TextureFormat.Depth32FloatStencil8] texture format. */
        public const val Depth32FloatStencil8: Int = 0x00000003

        /** Support for BC compressed texture formats. */
        public const val TextureCompressionBC: Int = 0x00000004

        /** Support for sliced 3D BC compressed texture formats. */
        public const val TextureCompressionBCSliced3D: Int = 0x00000005

        /** Support for ETC2 compressed texture formats. */
        public const val TextureCompressionETC2: Int = 0x00000006

        /** Support for ASTC compressed texture formats. */
        public const val TextureCompressionASTC: Int = 0x00000007

        /** Support for sliced 3D ASTC compressed texture formats. */
        public const val TextureCompressionASTCSliced3D: Int = 0x00000008

        /** Support for timestamp queries. */
        public const val TimestampQuery: Int = 0x00000009

        /** Support for `firstInstance` parameter in indirect draw calls. */
        public const val IndirectFirstInstance: Int = 0x0000000a

        /** Support for 16-bit floating-point types in WGSL. */
        public const val ShaderF16: Int = 0x0000000b

        /** Support for rendering to @see [TextureFormat.RG11B10Ufloat] textures. */
        public const val RG11B10UfloatRenderable: Int = 0x0000000c

        /** Support for using @see [TextureFormat.BGRA8Unorm] as a storage texture. */
        public const val BGRA8UnormStorage: Int = 0x0000000d

        /** Allows filtering of 32-bit float textures. */
        public const val Float32Filterable: Int = 0x0000000e

        /** Allows blending on 32-bit float render targets. */
        public const val Float32Blendable: Int = 0x0000000f

        /** Allows usage of clip distances in shaders. */
        public const val ClipDistances: Int = 0x00000010

        /** Allows blending with a second source color output from a fragment shader. */
        public const val DualSourceBlending: Int = 0x00000011

        /** Support for shader subgroup operations. */
        public const val Subgroups: Int = 0x00000012
        public const val TextureFormatsTier1: Int = 0x00000013
        public const val TextureFormatsTier2: Int = 0x00000014

        /**
         * Enables the primitive index feature, allowing fragment shaders to read the index of the
         * geometric primitive being rasterized.
         */
        public const val PrimitiveIndex: Int = 0x00000015

        /**
         * Enables the creation of texture views with a defined component swizzle, allowing the
         * remapping of the R, G, B, and A components during sampling.
         */
        public const val TextureComponentSwizzle: Int = 0x00000016
        internal val names: Map<Int, String> =
            mapOf(
                0x00000001 to "CoreFeaturesAndLimits",
                0x00000002 to "DepthClipControl",
                0x00000003 to "Depth32FloatStencil8",
                0x00000004 to "TextureCompressionBC",
                0x00000005 to "TextureCompressionBCSliced3D",
                0x00000006 to "TextureCompressionETC2",
                0x00000007 to "TextureCompressionASTC",
                0x00000008 to "TextureCompressionASTCSliced3D",
                0x00000009 to "TimestampQuery",
                0x0000000a to "IndirectFirstInstance",
                0x0000000b to "ShaderF16",
                0x0000000c to "RG11B10UfloatRenderable",
                0x0000000d to "BGRA8UnormStorage",
                0x0000000e to "Float32Filterable",
                0x0000000f to "Float32Blendable",
                0x00000010 to "ClipDistances",
                0x00000011 to "DualSourceBlending",
                0x00000012 to "Subgroups",
                0x00000013 to "TextureFormatsTier1",
                0x00000014 to "TextureFormatsTier2",
                0x00000015 to "PrimitiveIndex",
                0x00000016 to "TextureComponentSwizzle",
            )

        public fun toString(@FeatureName value: Int): String = names[value] ?: value.toString()
    }
}
