/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
@file:JvmName("Functions")

package androidx.webgpu

import dalvik.annotation.optimization.FastNative

public object GPU {

    /**
     * Creates a new WebGPU instance.
     *
     * @param descriptor The descriptor for the instance.
     * @return A handle to the created instance.
     */
    @Suppress("MissingJvmstatic")
    @FastNative
    public external fun createInstance(descriptor: GPUInstanceDescriptor? = null): GPUInstance

    /**
     * Retrieves the list of features supported by the instance.
     *
     * @param features A structure to be filled with the supported features.
     */
    @FastNative
    public external fun getInstanceFeatures(
        features: GPUSupportedInstanceFeatures
    ): GPUSupportedInstanceFeatures

    /**
     * Retrieves the limits supported by the instance.
     *
     * @param limits A structure to be filled with the supported limits.
     * @return The status of the operation.
     */
    @Suppress("MissingJvmstatic")
    @FastNative
    @Throws(WebGpuException::class)
    public external fun getInstanceLimits(
        limits: GPUInstanceLimits = GPUInstanceLimits()
    ): GPUInstanceLimits

    /**
     * Checks if a specific feature is supported by the instance.
     *
     * @param feature The feature to check for.
     * @return {@code true} if the feature is supported, {@code false} otherwise.
     */
    @FastNative public external fun hasInstanceFeature(@InstanceFeatureName feature: Int): Boolean
}
