/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes a buffer to be created. */
public class GPUBufferDescriptor(
    /** The allowed usages for the buffer. */
    @BufferUsage.Type public var usage: Int,
    /** The size of the buffer in bytes. */
    public var size: Long,
    /** A human-readable label for debugging. */
    public var label: String? = null,
    @get:JvmName("isMappedAtCreation") public var mappedAtCreation: Boolean = false,
) {
    /** Builder for [GPUBufferDescriptor]. */
    public class Builder(
        @BufferUsage.Type private val usage: Int,
        private val size: Long,
    ) {
        private var label: String? = null
        private var mappedAtCreation: Boolean = false

        public fun setLabel(label: String?): Builder = apply {
            this.label = label
        }

        public fun setMappedAtCreation(mappedAtCreation: Boolean): Builder = apply {
            this.mappedAtCreation = mappedAtCreation
        }

        /** Builds the [GPUBufferDescriptor]. */
        public fun build(): GPUBufferDescriptor =
            GPUBufferDescriptor(
                usage = usage,
                size = size,
                label = label,
                mappedAtCreation = mappedAtCreation,
            )
    }
}
