/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes a single resource binding within a bind group. */
public class GPUBindGroupEntry(
    /** The binding index corresponding to a shader resource. */
    public var binding: Int,
    /** The buffer to bind. Must be {@code null} if `sampler` or `textureView` is set. */
    public var buffer: GPUBuffer? = null,
    /** The offset in bytes from the beginning of the buffer. */
    public var offset: Long = 0,
    /** The size in bytes of the buffer binding. */
    public var size: Long = Constants.WHOLE_SIZE,
    /** The sampler to bind. Must be {@code null} if `buffer` or `textureView` is set. */
    public var sampler: GPUSampler? = null,
    public var textureView: GPUTextureView? = null,
) {

    /** Builder for [GPUBindGroupEntry]. */
    public class Builder(private val binding: Int) {
        private var buffer: GPUBuffer? = null
        private var offset: Long = 0
        private var size: Long = Constants.WHOLE_SIZE
        private var sampler: GPUSampler? = null
        private var textureView: GPUTextureView? = null

        public fun setBuffer(buffer: GPUBuffer?): Builder = apply { this.buffer = buffer }

        public fun setOffset(offset: Long): Builder = apply { this.offset = offset }

        public fun setSize(size: Long): Builder = apply { this.size = size }

        public fun setSampler(sampler: GPUSampler?): Builder = apply { this.sampler = sampler }

        public fun setTextureView(textureView: GPUTextureView?): Builder = apply {
            this.textureView = textureView
        }

        /** Builds the [GPUBindGroupEntry]. */
        public fun build(): GPUBindGroupEntry =
            GPUBindGroupEntry(
                binding = binding,
                buffer = buffer,
                offset = offset,
                size = size,
                sampler = sampler,
                textureView = textureView,
            )
    }
}
