/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes a single binding within a bind group layout. */
public class GPUBindGroupLayoutEntry(
    /** The binding index. */
    public var binding: Int,
    /** The shader stages in which the binding is visible. */
    @ShaderStage public var visibility: Int,
    public var bindingArraySize: Int = 0,
    /** The buffer binding layout. */
    public var buffer: GPUBufferBindingLayout =
        GPUBufferBindingLayout(type = BufferBindingType.BindingNotUsed),
    /** The sampler binding layout. */
    public var sampler: GPUSamplerBindingLayout =
        GPUSamplerBindingLayout(type = SamplerBindingType.BindingNotUsed),
    /** The texture binding layout. */
    public var texture: GPUTextureBindingLayout =
        GPUTextureBindingLayout(
            sampleType = TextureSampleType.BindingNotUsed,
            viewDimension = TextureViewDimension.Undefined,
        ),
    public var storageTexture: GPUStorageTextureBindingLayout =
        GPUStorageTextureBindingLayout(
            access = StorageTextureAccess.BindingNotUsed,
            format = TextureFormat.Undefined,
            viewDimension = TextureViewDimension.Undefined,
        ),
) {

    /** Builder for [GPUBindGroupLayoutEntry]. */
    public class Builder(private val binding: Int, @ShaderStage private val visibility: Int) {
        private var bindingArraySize: Int = 0
        private var buffer: GPUBufferBindingLayout =
            GPUBufferBindingLayout(type = BufferBindingType.BindingNotUsed)
        private var sampler: GPUSamplerBindingLayout =
            GPUSamplerBindingLayout(type = SamplerBindingType.BindingNotUsed)
        private var texture: GPUTextureBindingLayout =
            GPUTextureBindingLayout(
                sampleType = TextureSampleType.BindingNotUsed,
                viewDimension = TextureViewDimension.Undefined,
            )
        private var storageTexture: GPUStorageTextureBindingLayout =
            GPUStorageTextureBindingLayout(
                access = StorageTextureAccess.BindingNotUsed,
                format = TextureFormat.Undefined,
                viewDimension = TextureViewDimension.Undefined,
            )

        public fun setBindingArraySize(bindingArraySize: Int): Builder = apply {
            this.bindingArraySize = bindingArraySize
        }

        public fun setBuffer(buffer: GPUBufferBindingLayout): Builder = apply {
            this.buffer = buffer
        }

        public fun setSampler(sampler: GPUSamplerBindingLayout): Builder = apply {
            this.sampler = sampler
        }

        public fun setTexture(texture: GPUTextureBindingLayout): Builder = apply {
            this.texture = texture
        }

        public fun setStorageTexture(storageTexture: GPUStorageTextureBindingLayout): Builder =
            apply {
                this.storageTexture = storageTexture
            }

        /** Builds the [GPUBindGroupLayoutEntry]. */
        public fun build(): GPUBindGroupLayoutEntry =
            GPUBindGroupLayoutEntry(
                binding = binding,
                visibility = visibility,
                bindingArraySize = bindingArraySize,
                buffer = buffer,
                sampler = sampler,
                texture = texture,
                storageTexture = storageTexture,
            )
    }
}
