/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

public class GPUColorSpaceDawn(
    @ColorSpacePrimariesDawn.Type public var primaries: Int,
    @ColorSpaceTransferDawn.Type public var transfer: Int = ColorSpaceTransferDawn.Identity,
    @ColorSpaceYCbCrRangeDawn.Type public var yCbCrRange: Int = ColorSpaceYCbCrRangeDawn.Identity,
    @ColorSpaceYCbCrMatrixDawn.Type
    public var yCbCrMatrix: Int = ColorSpaceYCbCrMatrixDawn.Identity,
    public var hdrReferenceWhiteLuminance: Float = 0.0f,
) {
    /** Builder for [GPUColorSpaceDawn]. */
    public class Builder(@ColorSpacePrimariesDawn.Type private val primaries: Int) {
        @ColorSpaceTransferDawn.Type private var transfer: Int = ColorSpaceTransferDawn.Identity
        @ColorSpaceYCbCrRangeDawn.Type
        private var yCbCrRange: Int = ColorSpaceYCbCrRangeDawn.Identity
        @ColorSpaceYCbCrMatrixDawn.Type
        private var yCbCrMatrix: Int = ColorSpaceYCbCrMatrixDawn.Identity
        private var hdrReferenceWhiteLuminance: Float = 0.0f

        public fun setTransfer(@ColorSpaceTransferDawn.Type transfer: Int): Builder = apply {
            this.transfer = transfer
        }

        public fun setYCbCrRange(@ColorSpaceYCbCrRangeDawn.Type yCbCrRange: Int): Builder = apply {
            this.yCbCrRange = yCbCrRange
        }

        public fun setYCbCrMatrix(@ColorSpaceYCbCrMatrixDawn.Type yCbCrMatrix: Int): Builder =
            apply {
                this.yCbCrMatrix = yCbCrMatrix
            }

        public fun setHdrReferenceWhiteLuminance(hdrReferenceWhiteLuminance: Float): Builder =
            apply {
                this.hdrReferenceWhiteLuminance = hdrReferenceWhiteLuminance
            }

        /** Builds the [GPUColorSpaceDawn]. */
        public fun build(): GPUColorSpaceDawn =
            GPUColorSpaceDawn(
                primaries = primaries,
                transfer = transfer,
                yCbCrRange = yCbCrRange,
                yCbCrMatrix = yCbCrMatrix,
                hdrReferenceWhiteLuminance = hdrReferenceWhiteLuminance,
            )
    }
}
