/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

import dalvik.annotation.optimization.FastNative
import java.util.concurrent.Executor

/** A top-level object representing a WebGPU instance. */
public class GPUInstance private constructor(public val handle: Long) : AutoCloseable {
    /**
     * Creates a new surface.
     *
     * @param descriptor The descriptor for the surface.
     * @return The created surface.
     */
    @FastNative
    @JvmName("createSurface")
    @JvmOverloads
    public external fun createSurface(
        descriptor: GPUSurfaceDescriptor = GPUSurfaceDescriptor()
    ): GPUSurface

    /** Retrieves the list of WGSL language features supported by the instance. */
    @FastNative
    @JvmName("getWGSLLanguageFeatures")
    public external fun getWGSLLanguageFeatures(): GPUSupportedWGSLLanguageFeatures

    /**
     * Checks if a specific WGSL language feature is supported.
     *
     * @param feature The feature to check for.
     * @return {@code true} if the feature is supported, {@code false} otherwise.
     */
    @FastNative
    @JvmName("hasWGSLLanguageFeature")
    public external fun hasWGSLLanguageFeature(@WGSLLanguageFeatureName feature: Int): Boolean

    /** Processes pending asynchronous events and invokes their callbacks. */
    @FastNative @JvmName("processEvents") public external fun processEvents(): Unit

    /** Asynchronously requests a graphics adapter. */
    @FastNative
    @JvmName("requestAdapter")
    @JvmOverloads
    public external fun requestAdapter(
        callbackExecutor: java.util.concurrent.Executor,
        options: GPURequestAdapterOptions? = null,
        callback: GPURequestCallback<GPUAdapter>,
    ): Unit

    /**
     * Asynchronously requests a graphics adapter.
     *
     * @param options The options for the adapter request.
     */
    @Throws(WebGpuException::class)
    public suspend fun requestAdapter(options: GPURequestAdapterOptions? = null): GPUAdapter =
        awaitGPURequest { callback ->
            requestAdapter(Executor(Runnable::run), options, callback)
        }

    /**
     * Decrements the reference count of the object and frees resources when the count reaches zero.
     *
     * This is the standard way to manage object lifetimes and should be used in `use` blocks. After
     * calling this, the object is no longer usable.
     */
    external override fun close()

    override fun equals(other: Any?): Boolean = other is GPUInstance && other.handle == handle

    override fun hashCode(): Int = handle.hashCode()
}
