/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

import dalvik.annotation.optimization.FastNative
import java.nio.ByteBuffer
import java.util.concurrent.Executor

/** A queue for submitting command buffers to the GPU. */
public class GPUQueue private constructor(public val handle: Long) : AutoCloseable {
    /** Schedules a callback to be invoked when all previously submitted work is complete. */
    @FastNative
    @JvmName("onSubmittedWorkDone")
    public external fun onSubmittedWorkDone(
        callbackExecutor: java.util.concurrent.Executor,
        callback: GPURequestCallback<Unit>,
    ): Unit

    /** Schedules a callback to be invoked when all previously submitted work is complete. */
    @Throws(WebGpuException::class)
    public suspend fun onSubmittedWorkDone(): Unit = awaitGPURequest { callback ->
        onSubmittedWorkDone(Executor(Runnable::run), callback)
    }

    /**
     * Sets a human-readable label for debugging.
     *
     * @param label The label string.
     */
    @FastNative @JvmName("setLabel") public external fun setLabel(label: String): Unit

    /**
     * Submits a list of command buffers to be executed.
     *
     * @param commands An array of command buffers to submit.
     */
    @FastNative
    @JvmName("submit")
    @JvmOverloads
    public external fun submit(commands: Array<GPUCommandBuffer> = arrayOf()): Unit

    /**
     * Writes data to a buffer from the CPU.
     *
     * @param buffer The destination buffer.
     * @param bufferOffset The offset in the destination buffer.
     * @param data A pointer to the data to write.
     */
    @FastNative
    @JvmName("writeBuffer")
    public external fun writeBuffer(
        buffer: GPUBuffer,
        bufferOffset: Long,
        data: java.nio.ByteBuffer,
    ): Unit

    /**
     * Writes data to a texture from the CPU.
     *
     * @param destination The destination texture information.
     * @param data A pointer to the data to write.
     * @param writeSize The size of the region to write.
     * @param dataLayout The layout of the data in the source buffer.
     */
    @FastNative
    @JvmName("writeTexture")
    @JvmOverloads
    public external fun writeTexture(
        destination: GPUTexelCopyTextureInfo,
        data: java.nio.ByteBuffer,
        writeSize: GPUExtent3D,
        dataLayout: GPUTexelCopyBufferLayout = GPUTexelCopyBufferLayout(),
    ): Unit

    /**
     * Decrements the reference count of the object and frees resources when the count reaches zero.
     *
     * This is the standard way to manage object lifetimes and should be used in `use` blocks. After
     * calling this, the object is no longer usable.
     */
    external override fun close()

    override fun equals(other: Any?): Boolean = other is GPUQueue && other.handle == handle

    override fun hashCode(): Int = handle.hashCode()
}
