/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes a color attachment for a render pass. */
public class GPURenderPassColorAttachment(
    public var clearValue: GPUColor,
    /** The texture view for the color attachment. */
    public var view: GPUTextureView? = null,
    public var depthSlice: Int = Constants.DEPTH_SLICE_UNDEFINED,
    public var resolveTarget: GPUTextureView? = null,
    @LoadOp public var loadOp: Int = LoadOp.Undefined,
    @StoreOp public var storeOp: Int = StoreOp.Undefined,
) {

    /** Builder for [GPURenderPassColorAttachment]. */
    public class Builder(private val clearValue: GPUColor) {
        private var view: GPUTextureView? = null
        private var depthSlice: Int = Constants.DEPTH_SLICE_UNDEFINED
        private var resolveTarget: GPUTextureView? = null
        @LoadOp private var loadOp: Int = LoadOp.Undefined
        @StoreOp private var storeOp: Int = StoreOp.Undefined

        public fun setView(view: GPUTextureView?): Builder = apply { this.view = view }

        public fun setDepthSlice(depthSlice: Int): Builder = apply { this.depthSlice = depthSlice }

        public fun setResolveTarget(resolveTarget: GPUTextureView?): Builder = apply {
            this.resolveTarget = resolveTarget
        }

        public fun setLoadOp(@LoadOp loadOp: Int): Builder = apply { this.loadOp = loadOp }

        public fun setStoreOp(@StoreOp storeOp: Int): Builder = apply { this.storeOp = storeOp }

        /** Builds the [GPURenderPassColorAttachment]. */
        public fun build(): GPURenderPassColorAttachment =
            GPURenderPassColorAttachment(
                clearValue = clearValue,
                view = view,
                depthSlice = depthSlice,
                resolveTarget = resolveTarget,
                loadOp = loadOp,
                storeOp = storeOp,
            )
    }
}
