/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes a texture view. */
public class GPUTextureViewDescriptor(
    /** The usage of the texture view. */
    @TextureUsage public var usage: Int,
    /** A human-readable label for debugging. */
    public var label: String? = null,
    /** The format of the texture view. */
    @TextureFormat public var format: Int = TextureFormat.Undefined,
    /** The dimension of the texture view. */
    @TextureViewDimension public var dimension: Int = TextureViewDimension.Undefined,
    public var baseMipLevel: Int = 0,
    public var mipLevelCount: Int = Constants.MIP_LEVEL_COUNT_UNDEFINED,
    public var baseArrayLayer: Int = 0,
    public var arrayLayerCount: Int = Constants.ARRAY_LAYER_COUNT_UNDEFINED,
    /** The texture aspect for the view. Defaults to @see [TextureAspect.All]. */
    @TextureAspect public var aspect: Int = TextureAspect.All,
    /**
     * An extension chained to a texture view descriptor to define a custom component swizzle. This
     * allows remapping or forcing specific values for the R, G, B, and A channels when accessing
     * the texture view.
     */
    public var textureComponentSwizzleDescriptor: GPUTextureComponentSwizzleDescriptor? = null,
) {

    /** Builder for [GPUTextureViewDescriptor]. */
    public class Builder(@TextureUsage private val usage: Int) {
        private var label: String? = null
        @TextureFormat private var format: Int = TextureFormat.Undefined
        @TextureViewDimension private var dimension: Int = TextureViewDimension.Undefined
        private var baseMipLevel: Int = 0
        private var mipLevelCount: Int = Constants.MIP_LEVEL_COUNT_UNDEFINED
        private var baseArrayLayer: Int = 0
        private var arrayLayerCount: Int = Constants.ARRAY_LAYER_COUNT_UNDEFINED
        @TextureAspect private var aspect: Int = TextureAspect.All
        private var textureComponentSwizzleDescriptor: GPUTextureComponentSwizzleDescriptor? = null

        public fun setLabel(label: String?): Builder = apply { this.label = label }

        public fun setFormat(@TextureFormat format: Int): Builder = apply { this.format = format }

        public fun setDimension(@TextureViewDimension dimension: Int): Builder = apply {
            this.dimension = dimension
        }

        public fun setBaseMipLevel(baseMipLevel: Int): Builder = apply {
            this.baseMipLevel = baseMipLevel
        }

        public fun setMipLevelCount(mipLevelCount: Int): Builder = apply {
            this.mipLevelCount = mipLevelCount
        }

        public fun setBaseArrayLayer(baseArrayLayer: Int): Builder = apply {
            this.baseArrayLayer = baseArrayLayer
        }

        public fun setArrayLayerCount(arrayLayerCount: Int): Builder = apply {
            this.arrayLayerCount = arrayLayerCount
        }

        public fun setAspect(@TextureAspect aspect: Int): Builder = apply { this.aspect = aspect }

        public fun setTextureComponentSwizzleDescriptor(
            textureComponentSwizzleDescriptor: GPUTextureComponentSwizzleDescriptor?
        ): Builder = apply {
            this.textureComponentSwizzleDescriptor = textureComponentSwizzleDescriptor
        }

        /** Builds the [GPUTextureViewDescriptor]. */
        public fun build(): GPUTextureViewDescriptor =
            GPUTextureViewDescriptor(
                usage = usage,
                label = label,
                format = format,
                dimension = dimension,
                baseMipLevel = baseMipLevel,
                mipLevelCount = mipLevelCount,
                baseArrayLayer = baseArrayLayer,
                arrayLayerCount = arrayLayerCount,
                aspect = aspect,
                textureComponentSwizzleDescriptor = textureComponentSwizzleDescriptor,
            )
    }
}
