/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

import dalvik.annotation.optimization.FastNative

/** A GPU texture object. */
public class GPUTexture private constructor(public val handle: Long) : AutoCloseable {
    /**
     * Creates a new view of the texture.
     *
     * @param descriptor The descriptor for the texture view.
     * @return The created texture view.
     */
    @FastNative
    @JvmName("createView")
    @JvmOverloads
    public external fun createView(descriptor: GPUTextureViewDescriptor? = null): GPUTextureView

    /** Destroys the texture and releases its resources. */
    @FastNative @JvmName("destroy") public external fun destroy(): Unit

    /**
     * Gets the depth or number of array layers of the texture.
     *
     * @return The texture depth or layer count.
     */
    @FastNative @JvmName("getDepthOrArrayLayers") public external fun getDepthOrArrayLayers(): Int

    @get:JvmName("depthOrArrayLayers")
    public val depthOrArrayLayers: Int
        get() = getDepthOrArrayLayers()

    /**
     * Gets the dimension of the texture.
     *
     * @return The texture dimension.
     */
    @FastNative @JvmName("getDimension") @TextureDimension public external fun getDimension(): Int

    @get:JvmName("dimension")
    public val dimension: Int
        get() = getDimension()

    /**
     * Gets the format of the texture.
     *
     * @return The texture format.
     */
    @FastNative @JvmName("getFormat") @TextureFormat public external fun getFormat(): Int

    @get:JvmName("format")
    public val format: Int
        get() = getFormat()

    /**
     * Gets the height of the texture.
     *
     * @return The texture height.
     */
    @FastNative @JvmName("getHeight") public external fun getHeight(): Int

    @get:JvmName("height")
    public val height: Int
        get() = getHeight()

    /**
     * Gets the number of mipmap levels of the texture.
     *
     * @return The mipmap level count.
     */
    @FastNative @JvmName("getMipLevelCount") public external fun getMipLevelCount(): Int

    @get:JvmName("mipLevelCount")
    public val mipLevelCount: Int
        get() = getMipLevelCount()

    /**
     * Gets the sample count of the texture.
     *
     * @return The sample count.
     */
    @FastNative @JvmName("getSampleCount") public external fun getSampleCount(): Int

    @get:JvmName("sampleCount")
    public val sampleCount: Int
        get() = getSampleCount()

    @FastNative
    @JvmName("getTextureBindingViewDimension")
    @TextureViewDimension
    public external fun getTextureBindingViewDimension(): Int

    @get:JvmName("textureBindingViewDimension")
    public val textureBindingViewDimension: Int
        get() = getTextureBindingViewDimension()

    /**
     * Gets the allowed usages of the texture.
     *
     * @return The texture usage flags.
     */
    @FastNative @JvmName("getUsage") @TextureUsage public external fun getUsage(): Int

    @get:JvmName("usage")
    public val usage: Int
        get() = getUsage()

    /**
     * Gets the width of the texture.
     *
     * @return The texture width.
     */
    @FastNative @JvmName("getWidth") public external fun getWidth(): Int

    @get:JvmName("width")
    public val width: Int
        get() = getWidth()

    /**
     * Sets a human-readable label for debugging.
     *
     * @param label The label string.
     */
    @FastNative @JvmName("setLabel") public external fun setLabel(label: String): Unit

    /**
     * Decrements the reference count of the object and frees resources when the count reaches zero.
     *
     * This is the standard way to manage object lifetimes and should be used in `use` blocks. After
     * calling this, the object is no longer usable.
     */
    external override fun close()

    override fun equals(other: Any?): Boolean = other is GPUTexture && other.handle == handle

    override fun hashCode(): Int = handle.hashCode()
}
