/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: The KDocs in this file was generated by Google Gemini AI.
 * For the definitive source of truth, please refer to the source code and the official
 * WebGPU JS Specification (https://www.w3.org/TR/webgpu/).
 * If you find any inaccuracies, please file an issue with the Google Dawn team at
 * https://issuetracker.google.com/issues/new?component=1960262
 */
package androidx.webgpu

/** Describes the layout of a single vertex buffer. */
public class GPUVertexBufferLayout(
    public var arrayStride: Long,
    @VertexStepMode.Type public var stepMode: Int = VertexStepMode.Undefined,
    /** An array of vertex attributes sourced from this buffer. */
    public var attributes: Array<GPUVertexAttribute> = arrayOf(),
) {
    /** Builder for [GPUVertexBufferLayout]. */
    public class Builder(private val arrayStride: Long) {
        @VertexStepMode.Type private var stepMode: Int = VertexStepMode.Undefined
        private var attributes: Array<GPUVertexAttribute> = arrayOf()

        public fun setStepMode(@VertexStepMode.Type stepMode: Int): Builder = apply {
            this.stepMode = stepMode
        }

        public fun setAttributes(attributes: Array<GPUVertexAttribute>): Builder = apply {
            this.attributes = attributes
        }

        /** Builds the [GPUVertexBufferLayout]. */
        public fun build(): GPUVertexBufferLayout =
            GPUVertexBufferLayout(
                arrayStride = arrayStride,
                stepMode = stepMode,
                attributes = attributes,
            )
    }
}
