/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.health.connect.client.request

import android.annotation.SuppressLint
import android.net.Uri
import androidx.health.connect.client.HealthConnectFeatures
import androidx.health.connect.client.HealthConnectFeatures.Companion.FEATURE_PERSONAL_HEALTH_RECORD
import androidx.health.connect.client.feature.ExperimentalPersonalHealthRecordApi
import androidx.health.connect.client.feature.withPhrFeatureCheck
import androidx.health.connect.client.impl.platform.request.PlatformCreateMedicalDataSourceRequest
import androidx.health.connect.client.impl.platform.request.PlatformCreateMedicalDataSourceRequestBuilder
import androidx.health.connect.client.records.FhirVersion
import androidx.health.connect.client.records.toString
import kotlin.String

/**
 * A create request for
 * [androidx.health.connect.client.HealthConnectClient.createMedicalDataSource].
 *
 * The medical data is represented using the Fast Healthcare Interoperability Resources
 * ([FHIR](https://hl7.org/fhir/)) standard.
 *
 * This feature is dependent on the version of HealthConnect installed on the device. To check if
 * it's available call [HealthConnectFeatures.getFeatureStatus] and pass
 * [FEATURE_PERSONAL_HEALTH_RECORD] as an argument. An [UnsupportedOperationException] would be
 * thrown if the feature is not available.
 *
 * @property fhirBaseUri The FHIR base URI of the data source. For data coming from a FHIR server
 *   this should be the [FHIR base URL](https://hl7.org/fhir/R4/http.html#root) (e.g.
 *   `https://example.com/fhir/`). If the data is generated by an app without a FHIR URL,
 *   `fhirBaseUri` should be a unique and understandable URI defined by the app (e.g. `myapp://..`)
 *   that points to the source of the data. As an example, if a client app supports an
 *   [app deep linking](https://developer.android.com/training/app-links/deep-linking), this
 *   deeplink could be used as [fhirBaseUri]. The maximum length for the URI is 2000 characters.
 * @property displayName The display name that describes the data source. The maximum length for the
 *   display name is 90 characters. This must be unique per app.
 * @property fhirVersion The FHIR version of the medical data that will be linked to this data
 *   source. This has to be a version supported by Health Connect, as documented on the
 *   [FhirVersion].
 */
@ExperimentalPersonalHealthRecordApi
class CreateMedicalDataSourceRequest(
    val fhirBaseUri: Uri,
    val displayName: String,
    val fhirVersion: FhirVersion,
) {
    @SuppressLint("NewApi") // already checked with a feature availability check
    internal val platformCreateMedicalDataSourceRequest: PlatformCreateMedicalDataSourceRequest =
        withPhrFeatureCheck(this::class) {
            PlatformCreateMedicalDataSourceRequestBuilder(
                    fhirBaseUri,
                    displayName,
                    fhirVersion.platformFhirVersion,
                )
                .build()
        }

    override fun toString() =
        toString(
            this,
            mapOf(
                "fhirBaseUri" to fhirBaseUri,
                "displayName" to displayName,
                "fhirVersion" to fhirVersion,
            ),
        )

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CreateMedicalDataSourceRequest

        if (fhirBaseUri != other.fhirBaseUri) return false
        if (displayName != other.displayName) return false
        if (fhirVersion != other.fhirVersion) return false

        return true
    }

    override fun hashCode(): Int {
        var result = fhirBaseUri.hashCode()
        result = 31 * result + displayName.hashCode()
        result = 31 * result + fhirVersion.hashCode()
        return result
    }
}
