

package androidx.room3.integration.autovaluetestapp.vo;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_Mail extends Mail {

  private final String subject;

  private final String body;

  AutoValue_Mail(
      String subject,
      String body) {
    if (subject == null) {
      throw new NullPointerException("Null subject");
    }
    this.subject = subject;
    if (body == null) {
      throw new NullPointerException("Null body");
    }
    this.body = body;
  }

  @Override
  public String getSubject() {
    return subject;
  }

  @Override
  public String getBody() {
    return body;
  }

  @Override
  public String toString() {
    return "Mail{"
         + "subject=" + subject + ", "
         + "body=" + body
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Mail) {
      Mail that = (Mail) o;
      return this.subject.equals(that.getSubject())
          && this.body.equals(that.getBody());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= subject.hashCode();
    h$ *= 1000003;
    h$ ^= body.hashCode();
    return h$;
  }

}
