

package androidx.room3.integration.autovaluetestapp.vo;

import androidx.room3.Embedded;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_DogWithOwner extends DogWithOwner {

  @Embedded
  private final Pet.Dog dog;

  @Embedded
  private final Person owner;

  AutoValue_DogWithOwner(
      Pet.Dog dog,
      Person owner) {
    if (dog == null) {
      throw new NullPointerException("Null dog");
    }
    this.dog = dog;
    if (owner == null) {
      throw new NullPointerException("Null owner");
    }
    this.owner = owner;
  }

  @Embedded
  @Override
  public Pet.Dog getDog() {
    return dog;
  }

  @Embedded
  @Override
  public Person getOwner() {
    return owner;
  }

  @Override
  public String toString() {
    return "DogWithOwner{"
         + "dog=" + dog + ", "
         + "owner=" + owner
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof DogWithOwner) {
      DogWithOwner that = (DogWithOwner) o;
      return this.dog.equals(that.getDog())
          && this.owner.equals(that.getOwner());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= dog.hashCode();
    h$ *= 1000003;
    h$ ^= owner.hashCode();
    return h$;
  }

}
