/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.credentials.registry.digitalcredentials.openid4vci

import androidx.annotation.RestrictTo
import androidx.credentials.provider.ProviderCreateCredentialRequest
import androidx.credentials.registry.provider.selectedEntryMetadata
import org.json.JSONException
import org.json.JSONObject

/**
 * Metadata associated with a selected OpenID4VCI credential.
 *
 * This metadata is generated by the OpenID4VCI matcher during the matching process and is passed
 * back to the provider app.
 */
@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public class OpenId4VciSelectionMetadata
private constructor(
    /**
     * The ID of the matched entry within the [OpenId4VciDisplayData.entries] list of the
     * registration request. Matches [OpenId4VciDisplayData.Entry.id].
     */
    public val entryId: String,
    /**
     * The index of the matched sub-request within the `requests` array of the original digital
     * credential creation request. See the
     * [W3C Specification](https://www.w3.org/TR/digital-credentials/#the-digitalcredentialcreationoptions-dictionary)
     * for details.
     */
    public val requestIndex: Int,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is OpenId4VciSelectionMetadata) return false
        return this.entryId == other.entryId && this.requestIndex == other.requestIndex
    }

    override fun hashCode(): Int {
        var result = entryId.hashCode()
        result = 31 * result + requestIndex
        return result
    }

    override fun toString(): String {
        return "OpenId4VciSelectionMetadata(entryId=$entryId, requestIndex=$requestIndex)"
    }

    public companion object {
        private const val KEY_ENTRY_ID = "eid"
        private const val KEY_REQUEST_INDEX = "ridx"

        /**
         * Parses the [OpenId4VciSelectionMetadata] from a JSON string.
         *
         * @param metadataJson the JSON string containing the metadata
         * @return the parsed metadata
         * @throws JSONException if the JSON is malformed or missing required keys
         */
        @JvmStatic
        @Throws(JSONException::class)
        public fun parse(metadataJson: String): OpenId4VciSelectionMetadata {
            val json = JSONObject(metadataJson)
            return OpenId4VciSelectionMetadata(
                entryId = json.getString(KEY_ENTRY_ID),
                requestIndex = json.getInt(KEY_REQUEST_INDEX),
            )
        }
    }
}

/**
 * Returns the parsed [OpenId4VciSelectionMetadata] associated with the selected entry.
 *
 * A null return means that metadata isn't supported, wasn't provided, or failed to parse.
 */
@get:RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
public val ProviderCreateCredentialRequest.selectedOpenId4VciMetadata: OpenId4VciSelectionMetadata?
    get() {
        val metadataString = this.selectedEntryMetadata ?: return null
        return try {
            OpenId4VciSelectionMetadata.parse(metadataString)
        } catch (e: Exception) {
            null
        }
    }
