name: Compose Publish Dry Run
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - jb-main

jobs:
  compose-native-publish:
    runs-on: macos-15
    name: Dry Run Compose Publish Darwin + Native Linux
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Only save Gradle User Home state for builds on the 'jb-main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: false
          # Replace with this before merging
          # cache-read-only: ${{ github.ref != 'refs/heads/jb-main' }}

          # Limit the size of the cache entry.
          # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
          gradle-home-cache-excludes: |
            caches/jars-9
            caches/transforms-3

      - name: Compose Publish Darwin + Native Linux
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=macos,uikit,tvos,watchos,linux,mingw \
            --no-daemon --stacktrace

  compose-web-publish:
    runs-on: ubuntu-24.04
    name: Dry Run Compose Publish Web
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Only save Gradle User Home state for builds on the 'jb-main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: false
          # Replace with this before merging
          # cache-read-only: ${{ github.ref != 'refs/heads/jb-main' }}

          # Limit the size of the cache entry.
          # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
          gradle-home-cache-excludes: |
            caches/jars-9
            caches/transforms-3

      - name: Compose Publish Web
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=web \
            --no-daemon --stacktrace

  compose-jvm-publish:
    runs-on: ubuntu-24.04
    name: Dry Run Compose Publish JVM
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Only save Gradle User Home state for builds on the 'jb-main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: false
          # Replace with this before merging
          # cache-read-only: ${{ github.ref != 'refs/heads/jb-main' }}

          # Limit the size of the cache entry.
          # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
          gradle-home-cache-excludes: |
            caches/jars-9
            caches/transforms-3

      - name: Compose Publish JVM
        run: |
          ./gradlew publishComposeJb -Pcompose.platforms=jvm,android \
            --no-daemon --stacktrace
