name: "Prune old artifacts"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
permissions:
  actions: write
  contents: read

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: kolpav/purge-artifacts-action@04c636a505f26ebc82f8d070b202fb87ff572b10 # v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days

